### ISSUE TITLE
Installation error mysql on SSH of GCP

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#10]
mysql-server cannot be installed.
<br>
![installError](https://user-images.githubusercontent.com/55486644/84800621-09aa4680-b039-11ea-975d-556c4a618bda.JPG)

**Comment by 365kim** [comment]
웨-죠

**Comment by SeongsangCHO** [comment]
VM인스턴스의 운영체제르 demian -> ubuntu로 변경해서 해결했습니다.
