### ISSUE TITLE
Deploying the server on GCP

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#11]
### Deadline: 20200619(Fri)

- [x] To deploy our server so that we can connect it by external IP address.
 - [x] To connect yebalja.com domain and external IP on GCP so that we can connect our server by yebalja.com.
 - [ ] To figure out how to connect mysql db on GCP remotely.
 - [x] To learn React with Front-End team.

---

### 기한: 20200619(금)

- [x] GCP에 저희 서버를 올려서 외부 IP로 접속될 수 있게 합니다.
- [x] yebalja.com 도메인과 GCP 외부 IP를 연결해서 yebalja.com으로 접속될 수 있게 합니다.
- [ ] GCP에 올라가 있는 mysql db에 원격접속하는 방법을 알아봅니다.
- [x] 프론트엔드 팀과 함께 리액트 강의를 학습합니다.

**Comment by taelee42** [comment]
일단 1번은 완료했습니다.
급한불은 껐으니 2, 3번은 천천히 해도 될것 같습니다.
리액트 강의를 들으면서 2, 3번을 연구해 보도록 해요!

**Comment by taelee42** [comment]
## GCP에 있는 서버를 외부IP에서 접속하게 하는것을 완료하면서 알게된 사실은

1. GCP compute engine에 다른포트는 추가적인 설정없이는 못쓰는듯 합니다.
3000번 포트로 그렇게 접속하려 햇는데 방화벽문제로(추정?) 안된것 같습니다.
다만 3000번 포트의 방화벽을 열어줬음에도 불구하고 안된거라서 어떤 다른 설정이 필요한지는 좀 더 알아봐야합니다.

2. 기본 포트(80)을 사용하기 위해서는 sudo를 명령어 앞에 꼭 붙여야합니다.
다른포트가 안되므로 기본포트인 80(http의 경우)를 사용해야 하는데 기존 명령어로는 에러가 계속 떴습니다.
`Port 80 requires elevated privileges`
이 문제는 명령어 앞에 sudo를 붙여줌으로써 해결했습니다.

**Comment by SeongsangCHO** [comment]
서버구동시 sudo명령어를 붙여주어야 된다는 것을 확인했습니다.
2번의 도메인네임 연결은 GCP의 외부 IP를 연결해주면 사용가능합니다.

**Comment by taelee42** [comment]
성상님 덕분에 2번을 깔끔하게 완료했습니다.
프론트엔드팀과 함께 리액트 강의를 열심히 들어보죠.
3번은 리액트 강의듣다가 조금씩 시도해보겠습니다.

**Comment by taelee42** [comment]
3번은 아직 완성못했지만 당장 필요한게 아니라서 나중에 한거나 안하도록 결정했습니다.
이슈 닫겠습니다!!
