### ISSUE TITLE
[Dev_log] 16 June (Tue)

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#12]
###  `back-end`

- Deployed server to Google Cloud Platform (`taelee`, `secho`)

<br>

#### 1) node.js express-generator

- ##### Advantages

  - Easy to structure and manage `express` framework

- ##### Getting Started

  ```shell
  $ npm init
  $ npm install -g express-generator
  $ express . --view=pug
  ```

  - Essential elements and files, such as the defendencies list of `package.json`, are automatically created.

  - `node_module` should be placed in `.gitignore` as capacity is getting bigger. Each can be installed separately in local.

- ##### Directory Structure

  - bin : Manage  `www`  file.
  - pubilc : Manage static files such as images, style sheets, etc.
  - routes : Manage urls.
  - views : Manage templates such as html files.

- ##### Routing

  ```js
  res.send // to display directly on the screen
  res.sendFile // to display html files on the screen
  res.render // It's for us to use a template engines.
  ```

- ##### Error handling

  - 404 : When users go to a page that doesn't exist.
  - 500 : When there is a problem with the server.

#### 2) POST vs GET

- GET method attaches data to url and forwards it to the server.

  ```
  yebalja.com/?id=secho&pw=egoing
  ```

  In addition, there is a limit to the amount of data that can be sent (about 2000 bytes?)

- Using the POST method, data is not exposed and enters the `body` of `http.`

  - body-parser parses the requested data in POST method.

#### 3) MySQL workbench

- ##### Advantages

  - GUI

  - Automatically create a query statement for generate table.
  - Comments can be posted for each content
  - very easy insert & alter 
  - Easily view relationships between tables by image

- ##### [Reference](http://blog.naver.com/PostView.nhn?blogId=nateen7248&logNo=220490638560)

<br>

#### 1) template engine

- ##### pug

  - [Installation and Usage](https://lightcode.tistory.com/20 )

  - [Syntax](https://iseongho.github.io/posts/node-template-engine-pug/)
  - [official document](https://pugjs.org/language/tags.html)
  - [html-pug code converter](https://pugjs.org/language/tags.html)

- ##### ejs

  - The method of receiving data from `ejs` is the same. Use `res.render`

  - ```js
    app.set('view engine', 'ejs')
    ```

- ##### Advantages of Template Engine

  - If, loop, and variables make it easier to write html.

#### 2) framework

- ##### Front-end Framework TOP 3

  |               | **Angular** | **React**               | **Vue.js**         |
  | ------------- | ----------- | ----------------------- | ------------------ |
  | **Developer** | google      | facebook                | A Chinese          |
  | **feature**   | difficulty  | rising star (many data) | Losing Star (Easy) |

  - **[Reference](https://existek.com/blog/top-front-end-frameworks-2020/)**

- ##### 3 Advantages of React 

  1. Switch without loading when a button is clicked inside the page
  2. Web - Apps Can Be developed exactly the same.
  3. Reuse components
     - `yebalja.com` will have an advantage because there are many detailed pages with similar components.

<br>

## :paw_prints:​3. Decided

### 1) Front-end Framework 

- #### React !

  - Actually, they're all similar, so any framework would be nice to use, but... Decided by a large amount of data.

### 2) Issue

- Attach labels on a topic basis
- Publish freely with the meaning of discussions and records.
- Write Dev-log in issue.
  - regardless of back & front
  - On a meeting basis
  - Write in Korean & English both.
  - Comment on the contents of the meeting in Korean

#### <br>

## :paw_prints:​4. Thinking

### 1) How to apply MVC design pattern

- #### model

  - The usage of `models`directory in terms of MVC is vague unclear at the moment.
    - `taelee` "What about put only DB files in the directory ‘models’ Well.. It would make sense if the database gets complicated later."
    - `secho` "In my case, I created a config file in the `routes` directory to include all settings of the database. Only query statements in `models`"

- #### controller

  - Every route file needs one controller file in principle.
  - Will discuss it later when the structure gets more complicated

- #### view

  - Comparison of Template engine: pug vs ejs

  - The front-end team can ask the Back-end team to add some variables needed later on.

    

### 2) Whether to use the template engine

- Possibilities are that React can replace the template engine.
  - Will discuss it later after learning about React this week



### 3) Dev-log form

- The boundaries seem vague, but if you write one, it divides well... We're gonna get better, right?
  - done
  - learned
  - decided
  - think
  - to-do

<br>

## :paw_prints:​5. To-do

### `back-end`

- Remote access to DB (~ 6/19 Friday)
  - If difficult, create it with object.
- Deploy the server and connect url to yebalja.com (~ 6/19 Friday)

### `front-end`

- Listening to the lecture hard (~ 6/19 Friday)
  - ES2020 up to chapter4
  - react node bird up to chapter4
- I think it would be good to publish the issue about which classes to take. 



---



## :paw_prints:​1. 마무리했습니다.

###  `back-end`

- Google Cloud Platform에 서버 배포 (`taelee`, `secho`)

<br>

## :paw_prints:​2. 배웠습니다.

###  `back-end`

#### 1) node.js express-generator

- ##### 장점

  - express 프레임워크 구조화 및 관리 용이

- ##### 시작

  ```shell
  $ npm init
  $ npm install -g express-generator
  $ express . --view=pug
  ```

  - `package.json`의 dependencies list 등 필수요소 및 파일 촤라락 생성.

  - `node_module`은 용량이 점점 커져서 `git ignore`. 로컬서 각각 개별 설치

- ##### 디렉토리 구조

  - bin : `www` 실행파일 관리
  - pubilc : 이미지, 스타일시트 등 정적파일 관리
  - routes : url 관리
  - views : html 파일 등 templates 관리

- ##### 라우팅

  ```js
  res.send // 바로 화면에 띄우는것
  res.sendFile //html 파일을 화면에 쏴주는것
  res.render //템플릿엔진을 쏴주는것, 우리가 쓸것
  ```

- ##### 에러처리

  - 404 : 없는 페이지로 이동했을 때
  - 500 : 서버에 문제 생겼을 때

#### 2) POST vs GET

- get 방식은 데이터를 url에 붙여서 서버에 전달.

  ```
  yebalja.com/?id=secho&pw=egoing
  ```

  게다가 보낼 수 있는 데이터 크기에 한계가 있음 (약 2000바이트?)

- post 방식을 사용하면 데이터가 노출되지 않고 http의 body에 들어간다.

  - body-parser는 그 post로 요청된 데이터를 가공해준다.

#### 3) MySQL workbench

- ##### 특징

  - GUI 방식

- ##### 장점

  - 테이블 생성 쿼리문 자동으로 만들어줌
  - 콘텐츠마다 코멘트 달 수 있음
  - insert / alter 매우 쉬움
  - 테이블끼리 관계도 이미지로 쉽게 확인 가능
  - 만들어 놓은 쿼리문 전부 가져다가 복붙하면 다른 컴퓨터에서 사용할 때 편리

- ##### [참고 블로그](http://blog.naver.com/PostView.nhn?blogId=nateen7248&logNo=220490638560)

<br>

#### 1) template engine

- ##### pug

  - [pug 설치 및 적용법](https://lightcode.tistory.com/20 )

  - [pug 문법](https://iseongho.github.io/posts/node-template-engine-pug/)
  - [pug 공식문서](https://pugjs.org/language/tags.html)
  - [html-pug 코드변환기](https://pugjs.org/language/tags.html)

- ##### ejs

  - ejs에서 데이터 받는방법은 `res.render`로 똑같음

  - ```js
    app.set('view engine', 'ejs')
    ```

- ##### 템플릿 엔진의 장점

  - if, 반복문,변수를 쓸 수 있어서 html 작성 편리해짐

#### 2) framework

- ##### 프론트엔드 프레임워크에는 삼대장이 있음

  |        | Angular | React             | Vue.js         |
  | ------ | ------- | ----------------- | -------------- |
  | 만든이 | 구글    | 페이스북          | (☆) 중 국 ㅣ렉 |
  | 특징   | 어려움  | 뜬 별 (자료 많음) | 지는 별 (쉬움) |

  - [참고 자료](https://existek.com/blog/top-front-end-frameworks-2020/)

- ##### React 장점 3가지

  1. 페이지 내부에서 버튼 클릭했을때 로딩없이 전환
  2. 웹 - 앱 똑같이 구현 가능
  3. 컴포넌트 재사용
     - 예발자닷컴은 비슷한 컴포넌트를 가질 상세페이지가 많기 때문에 유리할듯

<br>

## :paw_prints:​3. 결정했습니다.

### 1) frontend 프레임워크

- #### React 사용하기로 결정!

  - 사실 셋 다 비슷해서, 어떤 프레임워크를 사용해도 좋겠지만... 자료가 많은 리액트로 결정.

### 2) Issue 활용방안

- 주제 단위로 label 붙이기
- 유용한 자료, 토론, 기록의 의미를 두고 자유롭게 발행하기
- 개발일지도 issue에 작성하기
  - 백/프론트 구분 없이
  - 회의 단위로 (주로 일단위)
  - 영어 / 한글 병기
  - 회의 내용에 대한 코멘트는 한글로

#### <br>

## :paw_prints:​ 4. 고민입니다.

### 1) MVC 디자인패턴 적용 방안

- #### model

  - models 디렉토리 활용성이 애매함.
    - `taelee` " models 폴더 만들어서 db 파일들만 모아놓까요? 흠.. 나중에 db가 복잡해지면 좋지만 지금은 굳이?"
    - `secho` "저는 db관련설정은 config파일에 넣고 라우트 폴더에서 불러와서 사용했습니다. models에는 쿼리문만 넣고."

- #### controller

  - 라우트파일마다 컨트롤러 파일 만드는게 원칙.
  - 일단 구조가 복잡해지면 도전하는 걸로.

- #### view

  - 템플릿 엔진 pug vs ejs
  - 파일 구성하다가 필요한 변수가 있으면 백에 요청하기



### 2) 템플릿엔진 사용여부

- react가 템플릿엔진을 대체할 수도 있다는 의견
  - 리액트 강의를 듣고 다시 고민해보기



### 3) 개발일지 양식

- 경계가 모호한 듯 하나 쓰다보면 잘 나뉘는 양식... 앞으로 발전하겠죠?
  - 마무리했습니다
  - 배웠습니다
  - 결정했습니다
  - 고민입니다
  - 할일

<br>

## :paw_prints:​ 5. 할 일이 있습니다. 

### `back-end`

- 데이터베이트 원격접속 (~ 6/19 금요일)
  - 만약 어려우면 오브젝트로 db 생성
- 서버 올려서 url yebalja.com에 연결 (~ 6/19 금요일)

### `front-end`

- 아직 구현 단계는 아니라고 보고, 강의 열심히 듣기 (~ 6/19 금요일)
  - ES2020 강의 4장까지
  - react node bird 강의 4장까지 
- 어떤 강의를 몇 강까지 들으면 좋을지 issue 파면 좋을 것 같아요.

**Comment by SeongsangCHO** [comment]
This dev-log reminded me of today's meeting.
I wrote a dev_log form.
Thanks!

---
오늘 미팅이 복기되었어요!
그리고 개발일지양식을 통일할 수 있도록 양식을 만들었습니다 [양식](https://github.com/FiveEat42/yebalja.com/wiki/Dev-log-form)

**Comment by taelee42** [comment]
회의록 자세하게 적어주셔서 감사드립니다!!
너무 깔끔해서 보기 좋은거 같아요 ㅎㅎ

**Comment by 365kim** [comment]
이것이 멋사운영진 클라스 인가요 ㅎ_
어제 수업만큼 알찬 회의록이네요 정리해주시느라 고생하셨구 감사합니다!!

**Comment by kirrikirri42** [comment]
깔끔한 정리 감사합니다!
