### ISSUE TITLE
Files on GCP has removed.

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#13]
![image](https://user-images.githubusercontent.com/55867479/84842111-3da85a80-b07f-11ea-8144-3ede9ea1cb04.png)

### Several things have changed
1. Yesterday, I changed ephemeral IP adress to static. But IP address has changed.
34.64.179.104->34.64.184.67

2. And name of server instance-1 was changed to instance-2

3. All the files and settings has been lost.

Yesterday, I tried to connect yebalja.com domain to gcp server. And then 404 traffic occurred. I doubted that it's attempt to connect from yebalja.com domain to GCP server. But I stopped server and slept. Why did it happened?

### 자고 일어났더니 gcp에 몇가지 변화가 생겼습니다.
1. 어제 외부 IP를 임시에서 고정을 바뀌어서 앞으로 바뀔일이 없다고 생각했는데 IP주소가 바뀌었습니다.
34.64.179.104->34.64.184.67

2. 원래 이름이 instance-1이었는데 instance-2로 바뀌었습니다.

3. 서버에 올려뒀던 모든 파일과 설정이 사라졌습니다.

의심되는 내용은 어제 제가 yebalja.com 도메인과 gcp를 연결하려고 했었는데 그때 gcp서버에 계속 404로 트래픽이 발생했었습니다. yebalja.com 도메인에서 gcp에 서버가 있는지 확인하는건가 싶기도 했는데 계속 404라 서버를 내리고 잠에 들었습니다. 왜 이럴까요?

**Comment by 365kim** [comment]
___whyrano?!___

**Comment by SeongsangCHO** [comment]
오마이갓
제가 어제 이것저것 안되서 VM인스턴스를 만들었다 삭제하기를 반복했는데
프로젝트공유가 되어서 그게 반영된게 아닐까요..?

**Comment by taelee42** [comment]
범인 검-거
