### ISSUE TITLE
Drafting the Main Page

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#14]
### Deadline: 2020. 06. 24(Wed)
- [x] Draft the main page

---
### 기한: 2020. 06. 24(수)
- 각자 메인페이지 초안을 짜봅니다

**Comment by 365kim** [comment]
두구두구....연간 캘린더 디자인....

**Comment by SeongsangCHO** [comment]
![draft](https://user-images.githubusercontent.com/55486644/85677878-ebaca800-b702-11ea-9362-4d3a720a456a.PNG)

**Comment by 365kim** [comment]
- 전체화면 네비게이션 바 구현
![cap1](https://user-images.githubusercontent.com/60066472/85677589-a2f4ef00-b702-11ea-98e5-b981bb37c6fd.PNG)
- 카드 구현
![cap2](https://user-images.githubusercontent.com/60066472/85677600-a5574900-b702-11ea-9610-cf40f6b30db6.PNG)
- 해상도 작을때
![cap3](https://user-images.githubusercontent.com/60066472/85677828-de8fb900-b702-11ea-868f-ca811e5a9f08.png)

**Comment by kirrikirri42** [comment]
- 톨니 스퇄(토니스타크스타일)로 Figma를 이용해 디자인해봤으나 작업량이 너무 많고 디자인이 아쉬워 폐기했습니다
![image](https://user-images.githubusercontent.com/52592748/85677640-adaf8400-b702-11ea-83a5-45ec9ec7ccab.png)
- 그 후 Figma로 깔끔한 Horizontal Timeline을 간략히 디자인해보았습니다
![image](https://user-images.githubusercontent.com/52592748/85677785-d3d52400-b702-11ea-86b0-8e77170ffeee.png)
- Material-ui component 사용법을 익혔고
![image](https://user-images.githubusercontent.com/52592748/85678051-139c0b80-b703-11ea-90be-248d4c5e22a1.png)
- 마음에 드는 색조합을 찾았으나
![image](https://user-images.githubusercontent.com/52592748/85679579-7f32a880-b704-11ea-9634-b853b5d3a34c.png)

- 원했던 Horizontal Timeline은 react자료로 찾을 수 없었습니다 
    - 따라서 Horizontal Timeline은 CSS형식으로 해봤습니다

![image](https://user-images.githubusercontent.com/52592748/85680037-e6505d00-b704-11ea-8346-d6c056a42d01.png)

![image](https://user-images.githubusercontent.com/52592748/85680127-f9632d00-b704-11ea-8fdc-200ca70d1614.png)

![image](https://user-images.githubusercontent.com/52592748/85679993-de90b880-b704-11ea-85f1-ee7b4173d4a9.png)

**Comment by hidaehyunlee** [comment]
![](https://user-images.githubusercontent.com/37580034/85753433-37814080-b747-11ea-80a4-856182eaf122.JPG)

![](https://user-images.githubusercontent.com/37580034/85753443-394b0400-b747-11ea-9b75-b0456fd04eef.JPG)

- 머티리얼UI에서 제공하는 컴포넌트들이 마음에 들지 않아서, 주로 구글링을 해서 템플릿을 찾았습니다. `awsome 30 react table template` 처럼 어-썸을 붙이는게 구글링 꿀팁.

-  주로 [codepen](https://codepen.io/) 이란 사이트로 많이 링크돼서, 여기서 많은 소스를 참고했습니다. 개인이 작성한 HTML, CSS, JavaScript 템플릿들을 공유하는 오픈소스 커뮤니티인 것 같아요. 

- 각 요소 별로 아래의 코드펜 템플릿을 이용해 만들었습니다.

  - ##### timeline

    - https://codepen.io/tutsplus/pen/ZKpNwm/
    - [사용법](https://webdesign.tutsplus.com/ko/tutorials/building-a-horizontal-timeline-with-css-and-javascript--cms-28378)

  - ##### table

    https://codepen.io/chriscoyier/pen/PgXRRM

  - ##### footer

    https://codepen.io/julesforrest/pen/qLpgNB
