### ISSUE TITLE
[Dev_log] 19 June (Fri)

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#15]
## 🐾 1. Done

- #### To deploy our server so that we can connect it by external IP address.

  - changed the port number to `80` and used `sudo`.

- #### To connect `yebalja.com` domain and external IP on GCP so that we can connect our server by `yebalja.com.`

  

<br>

## 🐾 2. Learned

- #### learned the basic course of `React`. 

- #### How to connect `react` and `node.js` servers and deploy.

  - node receives the `json` file, opens the DB, and react server receives the port number and displays it.

- #### React/CSS Honey  TIP 

  - ##### [MATERIAL-UI](https://material-ui.com/) 

    - React component design template

    - Use `CDN`

      ```html
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      ```

  - ##### [bootstapk](http://bootstrapk.com/getting-started/)

    - Use `CDN`

      ```html
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
      
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
      
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
      ```

  - ##### [CSS Image Sprite](https://github.com/365kim/web_study/blob/master/tutorial_CSS.md#3-1-%EC%9D%B4%EB%AF%B8%EC%A7%80)

    - Combine multiple images as one image
    - Requests to download to the web server as many images as possible to prevent the total loading time

  - ##### [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) 

    - Chrome Extensions
    - Can check React component code

  - ##### [Prettier](https://prettier.io/) 

    - Code formatter: format indent of js, json files.

  - ##### [Figma](www.figma.com) 

    - Home layout
    - `Yebalja.com` logo 
    - [draft made by `Jehong`](https://www.figma.com/file/lrkvFP4RGCBqZDZ966fLnA/Untitled?node-id=0%3A1)

  - ##### Free font 

    - [en](dafont.com)
    - [ko]( https://noonnu.cc/index)

  - ##### [goQuality-dev-contents](https://github.com/Integerous/goQuality-dev-contents/blob/master/README.md) 

<br>

## 🐾 3. Decided

- #### `Yebalja.com` logo

  - ko : [gmarket sans M](https://noonnu.cc/font_page/366)
  - en : [Staatliches](https://fonts.google.com/specimen/Staatliches)

![로고폰트_한영](https://user-images.githubusercontent.com/37580034/85189963-bd882c00-b2ee-11ea-9a46-37002a52e922.png)

<br>

## 🐾 4. Thinking

- #### Korean vs English main logo

  - Since the word `yebalja` is not an original English word, it seems that the meaning will not be caught immediately when written in English.
  - Since it is a word made with a combination of `Hangul`, why not use it in `Hangul`?

- #### Design main logo

  - Use the font until designed.

- #### `yebalja.com` Dev-history

  - 😂 *"Yebalja.com has made by 5 yebaljas."*  
  - Information about what lectures we learned to create yebalja.com
  - Information about which lecture is the latest.
  - Guidelines for how much you should listen to and start a project.

- #### IBM Clouders

  - [apply](https://developer.ibm.com/kr/clouders/) 
  - It still has benefits, so let's apply as a team.

<br>

### `back-end`

- #### To figure out how to connect mysql db on GCP remotely.

  - Front team access is required.

- #### Listen to the lecture of IBM Cloud Core  (~6/20)

### `front-end`

- ####  Draft the main page (~6/24 10am)

  - How to link detail page.
    - Use relative path.
    - `href="../index.html"`

---

<br>

## 🐾 1. 마무리했습니다.

- #### GCP에 저희 서버를 올려서 외부 IP로 접속될 수 있게 합니다.

  - 포트번호를 80로 바꾸고 sudo 명령어를 통해서 작동합니다.

- #### yebalja.com 도메인과 GCP 외부 IP를 연결해서 yebalja.com으로 접속될 수 있게 합니다.

<br>

## 🐾 2. 배웠습니다.

- #### 5명 모두 각자 `React` 기초 강의를 학습했습니다. 

- #### `react`와 `node.js` 서버를 연결해서 배포하는 방법.

  - 노드에서는 DB설정값이 들어있는 `json`파일을 받아 DB를 열거나 JS파일로 DB연동이 가능합니다. 
  - DB에서 얻은 데이터를 Json으로 node포트/URI로 전달한 다음, 해당 포트의 URI에 프록시가 중개매체 역할을 하여 리액트서버가 받아서 화면 출력합니다.

- #### 리액트/CSS 실무 TIP 

  - ##### [MATERIAL-UI](https://material-ui.com/) 

    - 리액트 컴포넌트 디자인 템플릿

    - 헤더에 `CDN`으로 연결

      ```html
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      ```

  - ##### [부트스트랩](http://bootstrapk.com/getting-started/)

    - `CDN`

      ```html
      <!-- 합쳐지고 최소화된 최신 CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
      
      <!-- 부가적인 테마 -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
      
      <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
      ```

  - ##### [이미지 스프라이트](https://github.com/365kim/web_study/blob/master/tutorial_CSS.md#3-1-%EC%9D%B4%EB%AF%B8%EC%A7%80)

    - 필요한 여러 개의 이미지를 하나로 합쳐서 사용하는 이미지
    - 이미지 수만큼 웹서버에 다운로드 요청해서 전체 로딩시간이 길어지는 것을 방지해줍니다.
    - 네이버나 다른 웹사이트들도 이미지스프라이트를 적용중입니다. 

  - ##### [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) 

    - 크롬 확장프로그램
    - react 컴포넌트 코드 확인하게 해줌

  - ##### [Prettier](https://prettier.io/) 플러그인

    - 코드 포멧터 : js, json 파일 인덴트 자동 정리

  - ##### [피그마](www.figma.com) 

    - 홈 레이아웃 구성
    - 예발자닷컴 로고 시안
    - [정아(jehong)님이 만드신 시안 링크](https://www.figma.com/file/lrkvFP4RGCBqZDZ966fLnA/Untitled?node-id=0%3A1)

  - ##### 무료 font 사이트 

    - [영어](dafont.com)
    - [한국어]( https://noonnu.cc/index)

  - ##### [고퀄리티⚡개발 컨텐츠 모음](https://github.com/Integerous/goQuality-dev-contents/blob/master/README.md) 

<br>

## 🐾 3. 결정했습니다.

- #### 예발자닷컴 로고

  - 한글 : [gmarket sans M](https://noonnu.cc/font_page/366)
  - 영어 : [Staatliches](https://fonts.google.com/specimen/Staatliches)

![로고폰트_한영](https://user-images.githubusercontent.com/37580034/85189963-bd882c00-b2ee-11ea-9a46-37002a52e922.png)

<br>

## 🐾 4. 고민입니다.

- #### 예발자닷컴 메인로고 한글vs영어

  - `예발자` 라는 말이 원래 있는 영단어가 아니기때문에 영어로 쓰면 바로 의미가 캐치되지 않을 것 같습니다. 
  - 한글 조합으로 만든 단어니까 한글로 하면 좋지 않을까?라고 고민중입니다.

- #### 로고는 폰트 쓰지말고 직접 디자인.

  - 일단 완성되기 전까지는 지정한 폰트로 사용해봅니다.

- #### 예발자 닷컴 개발 히스토리

  - *"예발자닷컴은 예발자 다섯이 모여 이렇게 만들었습니다."* (눈물)
  - 어떤 무료 강의들 들었는지 제공
  - 어떤 강의가 최신 자료인지 정보 추가
  - 어느정도 듣고 프로젝트를 시작하면 좋을지에 대한 가이드라인 

- #### IBM Clouders 지원할지 말지

  - [지원 링크](https://developer.ibm.com/kr/clouders/) 참고
  - 서버 쪽에 치우친 강의들이지만, CS학습하는데 도움이 될 것 같아요!
  - 그래도 혜택이 있으니, 팀으로 지원해봐요~!

<br>

### `back-end`

- #### GCP에 올라가 있는 mysql db에 원격접속하는 방법이 필요해요 

  - 프론트팀의 접근권한이 필요. 방법을 찾아야함. 더미데이터는 별로

- #### IBM Clouders Cloud Core 강의 듣기 (~6/20)

### `front-end`

- #### 예발자 닷컴 인덱스 페이지 프론트엔드로 구현해보기 (~6/24 오전10시)

  - 서버구동없이 디테일 페이지 링크 거는 법.
    - 상대경로로 지정해서 이동할 수 있어요.
    - `href="../index.html"`

**Comment by SeongsangCHO** [comment]
깔끔한 정리! 감사합니다 ㅎㅎ

Honey TIP!!

**Comment by 365kim** [comment]
___"예발자닷컴은 예발자 다섯이 모여 이렇게 만들었습니다." (눈물)___ 에서 울컥했습니다
감동적인 데브로그에요...
깔끔하고 알차게 정리해주셔서 감사합니다!!

**Comment by 365kim** [comment]
- __부트스트랩 vs Material-UI 비교__
<br>
![비교](https://user-images.githubusercontent.com/60066472/85190517-21f9ba00-b2f4-11ea-8ed4-80647dbd752d.PNG)
[원문 링크](https://flatlogic.com/blog/bootstrap-vs-material-ui-which-one-to-use-for-the-next-web-app/)
- __둘다 적용하는 방법?__
    - 부트스트랩을 적용해서 해상도에 따라 일일이 코딩하는 번거로움을 줄이고, 구글의material 디자인을 적용해서 깔끔한 디자인도 가져가고 싶다면: __Material Design for Bootstrap__
[데모 페이지](https://react.mdbootstrap.com/)

**Comment by 365kim** [comment]
https://getmdl.io/components/index.html
구글이 낸것도 있네요..!

**Comment by kirrikirri42** [comment]
정리 감사합니다 ㅎㅎ
개발 히스토리와 예발자 로고에 대해 토의하다니 뭔가 역사적인 날이군여..!!
