### ISSUE TITLE
Annual calendar design issues 

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#16]
# Annual calendar design issues 

#### 1. Problems with annual calendar design

- There are 5 free courses we offer, but the recruitment start date is concentrated at the beginning of this year~June. Don't you think leaving the rest of July and December blank would be a waste of space or design?
- Annual calendar information cannot be delivered well in a mobile environment.

<br>

#### 2. Suggestions for high-quality design

1. In terms of design, I think the calendar like an Excel table is ambiguous.

2. In the main page, is it necessary to provide information such as interview date/acceptance date?

   - I think the most important information for the user is the `recruitment start date`.

3. If we only offer the recruitment start date/program name in main page, we don't need to stick to the calendar design.

4. I think the two issues below can be solved by using the timeline format instead of the calendar.

   1. Clean and simple design
   2. Web and mobile design concept clash

5. I think it might be more appropriate to make a detailed page of the recruitment schedule in the form of a timeline. It has the advantage of being able to give a sense of unity to the entire website...

6. `timeline` design Reference 

   - [Main Page/Vertical Type](https://codyhouse.co/demo/vertical-timeline/index.html#0)

   - [Detailed page/Horizontal type](https://codyhouse.co/demo/horizontal-timeline/index.html)

   - Main page/horizontal type<p><img src="https://user-images.githubusercontent.com/37580034/85206488-72f1c880-b35d-11ea-9759-6b0d901b14f7.jpg" width="500"></p>

---

<br>

# 연간일정표에 관한 프론트 이슈

#### 1. 연간일정표 디자인의 문제점

- 우리가 제공하는 무료 코스가 5개인데, 모집시작일이 연초-6월에 몰려있음. 나머지 7월~12월을 빈칸으로 두는게 공간낭비 혹은 디자인 적으로 허전한 느낌이지 않을까?
- 모바일 환경에서는 연간일정표 정보를 잘 전달하기 힘들 것 같음.

<br>

#### 2. 높은 완성도의 쿨하고 깔끔한 디자인을 위한 제안

1. 디자인 측면에서 엑셀표같은 느낌의 달력은 애매하다는 생각.

2. 메인 페이지에서 모집 시작일 외 면접일/합격발표일 같은 정보를 굳이 제공할 필요가 있을까? 

   - 사용자에게 가장 중요한 정보는 `모집 시작일`이지 않을까요?

3. 모집시작일/프로그램명만 보여줄거면 굳이 달력 디자인을 고수하지 않아도 될 것 같음.

4. 달력말고 타임라인 형태로 하면 아래 두가지 이슈를 해결할 수 있을 것 같음.

   1. 깔끔하고 단순한 디자인 
   2. 웹과 모바일 디자인 컨셉의 충돌  

5. 아예 모집일정 상세 페이지도 타임라인 형태로 하는게 더 적절할 수도 있다는 생각. 전체 웹사이트 디자인 통일감을 줄수 있다는 장점도 있고... 

6. 참고할만한 `타임라인` 디자인

   - [메인페이지/세로형](https://codyhouse.co/demo/vertical-timeline/index.html#0)

   - [상세페이지/가로형](https://codyhouse.co/demo/horizontal-timeline/index.html)

   - 메인페이지/가로형<p><img src="https://user-images.githubusercontent.com/37580034/85206488-72f1c880-b35d-11ea-9759-6b0d901b14f7.jpg" width="500"></p>

**Comment by hidaehyunlee** [comment]
![image](https://user-images.githubusercontent.com/37580034/85206900-35db0580-b360-11ea-8d9e-6d21ba198cda.png)

(모바일에서) 이 세로 타임라인 어떤가요? 저 타임라인 아이콘 대신 월/시작날짜가 들어가 있으면 타임라인 디자인+리스트 디자인 둘 다 만족할 수 있어서 넘 좋을 것 같은데...
😧 왜 타임라인에 꽂힌걸까요 😨

**Comment by 365kim** [comment]
반응형으로 하면 웹/앱 한번에 해결되서 무조건 좋은 건줄 알았는데
컨텐츠 형태의 한계가 생기네요...!!
좋은 고민거리 던져주셔서 감사합니다!!

오 저렇게 하면 불필요하게 낭비되는 공간도 없앨 수 있어서
정보전달 측면에서나 디자인 측면에서 모두 좋을 것 같아요!

연간일정을 화면에 뿌려내기가 어려울 것 같긴한데
처음 연간일정을 논의할 때 그 갬동에 아직 미련이 남아서 ㅎㅎ 연간일정 조금만 더 파보겠습니다! 😆

**Comment by taelee42** [comment]
상세페이지에 타임라인을 고려하는건 괜찮은데 전체적인 느낌을 한번에 제공하는 메인페이지에서 스크롤이 있으면 한눈에 안들어오지 않을까 싶네요
모바일과 함께 고려하면 쉽지 않으니 일단 웹에 최적화될 수 있도록 생각해볼까요?
또 연간일정이 상세페이지보다는 어려운편이니 상세페이지를 먼저 시작해봐도 괜찮고요
(둘다 달력이니깐 월간을 하다보면 연간의 힌트로 얻을 수 있지 않을까 싶어서요)

모바일까지 고려한다면 메인페이지에서
웹: 연간달력, 프로그램 비교
모바일: 프로그램 비교만
하는것도 괜찮은거 같습니다

웹, 모바일 둘다 있는 사이트들에서 모바일 페이지에서는 화면 크기 상의 문제로 정보를 생략하는 경우도 많은것 같아서요

**Comment by kirrikirri42** [comment]
1. 연간일정표에서 비어있는 달들이 많아 저도 좀 아쉽다고 느꼈었는데 좋은 점 지적해주신 것 같습니다!

- 이건 대리님이 그려주신 타임라인 형태를 이용하면 좋을 것 같네요

- 월을 작게 표시하면 1~12월을 다 넣어도 전혀 문제없을 것 같습니다

- 그리고 "간지"나게 마치 AR 화면이나 아이언맨 스크린에 정보 촤라락 뜨는 것처럼 디자인하면 어떨까 조심스레 생각해봤습니다.
![Screen Shot 2020-06-20 at 23 45 16](https://user-images.githubusercontent.com/52592748/85215720-8df12680-b3b7-11ea-89f8-23508881ec94.png)
![Screen Shot 2020-06-20 at 23 39 11](https://user-images.githubusercontent.com/52592748/85215722-921d4400-b3b7-11ea-872c-13c36b01311d.png)
![Screen Shot 2020-06-20 at 23 34 51](https://user-images.githubusercontent.com/52592748/85215725-93e70780-b3b7-11ea-9c4b-35597a3b0e06.png)


---


2. 모바일 화면은 저도 생각치 못했던 부분인데 아주 좋은 고민거리인 것 같습니다!

- 모바일웹은 성상님이 카톡에 공유해주신 자소서닷컴 모바일웹의 **리스트 형식**이 좋아보입니다
  ![image](https://user-images.githubusercontent.com/52592748/85215639-b9274600-b3b6-11ea-8e73-4fde634cffc2.png)
  웹이든 모바일웹이든 **한 눈에** 다양한 정보가 보이는게 제일 좋다고 생각합니다

- 위의 리스트 형식 앞에 모집 날짜만 추가해준다면 고대로 타임라인형식이 되겠네요

- 다만 우리가 아직 웹만으로도 벅차서 일단은 웹에만 집중하는게 나을 거 같습니다 ㅎㅎ

**Comment by SeongsangCHO** [comment]
대리님의 의견덕분에 기기별로 특성을 고려해야한다는 것을 알게되었습니다..!

모바일은 세로로 자세하게 볼 수 있고 웹은 가로로 길게 전체적인 내용을 한눈에 볼 수 있다는 점을 염두에 두어야겠습니다.

타임라인을 모듈화하여 조금씩 변형하면 웹, 모바일 둘다 사용할 수 있지 않을까 생각합니다.


다만, 아직 구현전이기도 하고 사용자의 입장에서 뭐가 더 좋아보일지 몰라서 결정하기가 어렵네요. 웹 기준으로 먼저 구현해보도록 하겠습니다.
