### ISSUE TITLE
Need to think about Statistic features about visitors.

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#19]
It would be better to make statistic features on 'yebalja.com'
To know how much users visit our site, let's make those features before the launching our site.
How do you think? 

ex) the number of users, location where they visit, etc

---

방문자 생기면 페이지에 나오지 않더라도 내부적으로 통계지표들이 집계되면 좋을것 같습니다.
런칭되기전에 구현해서 초기런칭때부터 방문자수를 알 수 있으면 좋을거 같아요
어떻게 생각하시나요?

예) 접속자수, 접속위치 등등?

**Comment by 365kim** [comment]
오 생각해보지 못했지만 꼭 필요한 기능인 것 같습니니다.

**Comment by SeongsangCHO** [comment]
좋은 기능인거 같습니다!

**Comment by kirrikirri42** [comment]
아주 좋습니당!

**Comment by taelee42** [comment]
구글 애널리틱스라는게 있는데 
가입하고 저기서 제공하는 코드를 저희가 갖고 있는 모든 페이지 Head에 넣으면 통계를 분석해준다고 하네요.

랜딩페이지: 어떤 페이지로 들어왔는지
Exit Point: 어떤 페이지에서 나갔는지(마지막으로 머무른 페이지)
방문자수 등등 여러 통계수치를 제공해주네요

페이지들이 구성되면 적용해보겠습니다~!

**Comment by taelee42** [comment]
구글 애널리틱스를 어떻게 하는지 조사했으니 배포하기 전에 모든 페이지에 삽입하면 될 것 같습니다.
