### ISSUE TITLE
Need to deploy our site based on daelee's code to GCP

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#20]
Back todo list
- [x] To deploy Daelee's code on GCP.
- [x] To connect yebalja.com to GCP
- [x] To make DB from Yearly timeline data
- [ ] To make SSL certificate to let connect our site by HTTPS
- [ ] To help Daelee's work(React Timeline)

Non priority list
- [ ] To make DB from comparison table
- [x] To implement login feature
---

백 할일
- [x] 대리님 코드로 gcp 서버에 올려서 작동해보기
- [x] yebalja.com 에서 볼수있게 하기
- [x] 연간에 있는 타임라인 db화 해보기(타임라인이 상세로 가더라도 양식이 비슷하기때문에 미리해도 될거 같아서)
- [ ] ssl 인증서 받아서 https로 접속할 수 있게 만들기
- [ ] 대리님 리액트 타임라인 도와주기

천천히 할일
- [ ] 표는 나중에 db화 하기?(db의 형태가 바뀔거 같아서)
- [x] 로그인은 천천히

**Comment by SeongsangCHO** [comment]
확인했습니다~~ㅎㅎ
