### ISSUE TITLE
Need to Develop the 'Home' page

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#21]
### Deadline: 2020. 07. 07(Tue)
- Develop the 'Home' page
    - Implement the Yearly Calendar __(daelee + mihykim,jehong)__
        - [x] Analyze and understand jsainsburypl's code
        - [x] (as-is) quarter / month > (to-be) month / week
        - [x] add 'year' colum
        - [x] make it possible to process input by 'date'
    - Implement the Comparison table __(jehong)__
        - [x] Arrange all information of 7 bootcamps in one table
        - [x] Apply responsive design
    - Design an illustration for the jumbotron __(jehong)__
        - [x] Draw and paint the illustration
        - [x] Add animation
        - [x] Put in code (svg)
    - Implement major components __(mihykim)__
        - [x] Header
        - [x] Navbar
        - [x] Jumbotron
        - [x] Footer
- Add the coding convention if needed

---
### 기한: 2020. 07. 07 (화)
- 'Home' 페이지를 디벨롭합니다.
    - 연간일정 구현 __(대현 + 미혜,정아)__
        - jsainsburyplc 코드 분석
        - (기존) 분기 / 월 > (변경) 월 / 주
        - 연간 행 추가
        - 날짜 단위로 입력 받을 수 있도록 하기
    - 비교 표 구현 __(정아)__
        - 7개요소 모두 포함하도록 배치
        - 반응형 적용
    - 예발자닷컴 전용 점보트론용 일러스트 디자인 __(정아)__
        - 일러스트 컷 드로잉 및 채색
        - 애니메이션 적용
        - 코드에 적용
    - 홈 화면 주요 컴포넌트 구현 __(미혜)__
        - 헤더
        - 내비바
        - 점보트론
        - 푸터
- 필요시 코딩컨벤션을 추가합니다.

**Comment by taelee42** [comment]
기한에서 영어와 한글이 다른것 같아요!

**Comment by 365kim** [comment]
__넣고싶은 컴포넌트 목록__
(내일 추가될 예정) (아마도)

**Comment by hidaehyunlee** [comment]
> **넣고싶은 컴포넌트 목록**
> https://codepen.io/dev_loop/pen/MWKbJmO Image Slider 예뻐서 추가
> https://codepen.io/Akimzzy/pen/JjGKMoX Full Screen Slider 멋있어서 추가
> https://codepen.io/ricardoolivaalonso/pen/oNjdBme Dog 귀여워서 추가...

**Comment by hidaehyunlee** [comment]
- [Vertical Timeline](https://codepen.io/flavioschneider/pen/ByVGGx) (타임라인만 보면 수집하는 병)

- Card UI
  - https://codepen.io/wintr/pen/zKzRXQ
  - https://codepen.io/ariona/pen/JYGzBB
  - [profile card](https://codepen.io/Mestika/pen/KVXVWE)

- [Calendar](https://codepen.io/Jackthomsonn/pen/pyjXdJ)

- [Nav Bar](https://codepen.io/chrisdwheatley/pen/cFtzb)

- [Scroll Animation](https://codepen.io/balapa/pen/vLzmmM)

(추가 예정..)

**Comment by kirrikirri42** [comment]
**라이센스**
[Codepen License 공개된 것은 MIT License라고 합니다](https://blog.codepen.io/documentation/licensing/)
하지만 해당 코드가 남의 그림이나 폰트를 가져다 썼다면 아마 문제가 되지않을까 싶습니다

---

**컴포넌트 목록**

- 메일로 구독하세요~
[메일 구독 창](https://codepen.io/ahmedhosna95/pen/BaNQweQ)
[메일 구독 애니메이션 창](https://codepen.io/BeanBaag/pen/mMJqma)

- 구독자가 받는 이메일
[구독한 사람들에게 보내는 메일 요정도로 간단한게 좋을 것 같아요](https://codepen.io/luckyyang/pen/vzkoi)

-  로딩
[봉고캣이 코딩하는거](https://codepen.io/carolineartz/pen/VwYwZaP)
[봉고캣이 코딩하는거 형관 버전](https://codepen.io/carolineartz/pen/qBOEzQa)
[손가락 태핑하며 기다리는 거](https://codepen.io/littleberry/pen/BLjAJY)

- 우리 예발자 소개 페이지에 쓰면 좋을 것 멋있을 것 같아요
[타이핑 효과 신기해서](https://codepen.io/lefourbefromage/pen/qBbZWEJ)

---

**여기서부터는 쓸데없는 것들입니다**

[타이틀 나타나는 효과 멋있어서](https://codepen.io/RobinTreur/pen/pyWLeB)
[혹시 우리가 dark mode 같은 걸 지원하는 경우가 생긴다면](https://codepen.io/AngelaVelasquez/pen/tjzaG)

- 혹시 나중에 쉬어가는 공간? 혹은 뭐 그냥 후기 페이지같은 곳에 간단하고 재밌는 게임같은 것을 추가한다면?
[버튼을 클릭하라고 하지만 클릭할 수가 없습니다](https://codepen.io/bnhovde/pen/OJLYGKx)
[버튼을 눌러보며 캐릭터의 행동을 볼 수 있습니다](https://codepen.io/bnhovde/pen/WMgbEa)

- 로딩..을 가장한 맘에 드는 애니메이션 목록
[고양이 발바닥 남기는거](https://codepen.io/motionimaging/details/MKrQXa)
[권총 총알 하나씩 추가되며 돌아가는 모션](https://codepen.io/dfitzy/pen/XdaoWg)
[저도 Dog 귀여워서.. 통통한 허스키](https://codepen.io/davidkpiano/pen/wMqXea)
[성상님을 위한 감자튀김 비](https://codepen.io/giuliacardieri/pen/vZGRbL)
[감자튀김 먹으면서 기다리기](https://codepen.io/agoodwin/pen/jaypGP)
[채팅하는 고양이와 강아지](https://codepen.io/clarawrsong/pen/JMMdOz)
[놀아달라는 강아지](https://codepen.io/davidkpiano/pen/kkpGWj)
[꼬리 흔드는 강아지](https://codepen.io/Kozelskiy/pen/QpYooq)
[빠르게 날아가는 모습](https://codepen.io/mr_alien/pen/FDLjg)
