### ISSUE TITLE
[Interim Review] 27 June (Sat)

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#24]
## 🐾  Taelee

- Deployed `react` code that Daelee made on the GCP server with Secho
- To deploy that server with `express`, I'm watching zerocho's `react` lecture 

## 🐾  Secho

- Thinking 1:  Making a server with`React + Express`  and `next + Express` are different.

  - The way with `React + Express`, I pass back-end data by json file

    but the latter may be passed by `view.html` files

- Thinking 2: Is `.next` folder of static files like `build` folder that made from `npm run build` in CRA(Create React App)

  - Taelee: `.next` might be cache files and therer is another command to make static files (`next build`)

- SSR explained
  - When using `React`, it's worked by CSR(Cline Side Rendering). Back-end pass empth html file to front-end and then html file will be filled with data that will be passed after.(Rendering by Client, Initial speed is slow)
  - At this time, search engine visits the site and decide this site is empth. So the site won't be shown in the search result.
  - If you use next next does SSR(Server Sider Rendering), it renders only one time when users visit it. So the problem is resolved

## 🐾  Mihykim

- Could Sehco explain SSR with our site
  
- Secho: Sure
  
- Won't `next` be changed to other framework?

  - Taelee, Secho: It doesn't matter

  - Daelee: `next` and `react` aren't different too much. So it won't be not that hard.

    

## 🐾  Daelee 

- Question: How to apply css stylie in `next`
  - Applied from css file
    - import styles from './styles.css';
  - In a function, import style.jsx file and apply it(It's called css-in-js or styled-jsx)
    - [Referenece site1](https://brunch.co.kr/@hee072794/89)
    - [Referenece site2](https://blog.woolta.com/categories/1/posts/185)

## 🐾  Jehong

- I put some thought into table
  - [Candidate  1](https://codepen.io/lukepeters/pen/bfFur)
<p><img src="https://user-images.githubusercontent.com/55867479/85917963-ae2e5300-b899-11ea-8551-58ad2267fe68.png" width=500></p>
<p><img src="https://user-images.githubusercontent.com/55867479/85917975-c1d9b980-b899-11ea-8cb4-8d07ccaa6c69.png" width=500></p>

  - Candidate 2 : Header is not changed, and contents are disappeared until one content column is left
    - Opinion: It's okay to show 2 columns
<p><img src="https://user-images.githubusercontent.com/55867479/85918020-0b2a0900-b89a-11ea-9c29-1561b9d5dcc0.png" width=200></p>

  - [Candidate 3](https://codepen.io/ralphsaniatan/full/ZEGaqgw)  (Mihykim's opinion) : There's a lot of room for improvement, but it's good to refer to
<p><img src="https://user-images.githubusercontent.com/55867479/85918013-05342800-b89a-11ea-92b8-b479c901616e.png" width=700></p>

<p><img src="https://user-images.githubusercontent.com/55867479/85918004-ef266780-b899-11ea-9881-f3c969b8311b.png" width=400></p>

---

## 🐾  태혁

- 성상님과 함께 GCP에 대현님이 만든 리액트 서버를 올려봤습니다.
- 익스프레스 서버도 함께 올려야하므로 합치는 방법을 알기 위해 제로초님 강의를 듣고 있습니다.

## 🐾  성상

- 고민1: 기존 `React + Express` 방식과 `next + Express`방식에 차이가 있는 것 같습니다.

  - 기존에는 백에서 json파일로 프론트에게 정보를 넘겨주었는데

    넥스트와 함께 쓰면 view.html로 넘겨줘야하나 고민입니다.

- 고민2: CRA(Create React App)에서 npm run build로 build폴더가 만들어지는 것처럼 .next도 `next`에서 만들어진 정적 파일인가요?

  - 태혁: .next는 `next`의 캐싱파일인것 같습니다. `next`의 경우 `next build`가 따로 있는것 같습니다.

- SSR의 간단설명
  - 리액트를 사용하면 CSR(Client Side Rendering)이 일어나는데 이 경우 처음에 html파일은 내용이 없고 서버에서 데이터를 받아서 내용이 채워짐(클라이언트에서 렌더링을 진행함, 초기속도가 느림)
  - 이 때, 검색엔진이 사이트를 방문하고 아무것도 없다고 인식해서 검색결과에 노출시켜 주지 않음
  - next는 SSR(Server Sider Rendering)을 통해 첫방문때만 서버쪽에서 다 렌더링을해서 완성된 html파일을 클라이언트에게 보내주어 위 문제를 해결함

## 🐾  미혜

- 성상님이 SSR(Server Side Rendering) 발표하실 때 yebalja.com의 작동원리도 같이 설명해 주실 수 있을까요?
  
- 성상: 물론입니다
  
- 앞으로 next에서 바뀌진 않을까요?

  - 태혁: 쓰면 좋고 안써도 괜찮습니다.

  - 성상: 써도 안 써도 상관없습니다.

  - 대현: `next`가 `react`와 크게 다르지 않아 사용하는데 큰 불편함이 없을 것 같습니다.

    

## 🐾  대현 

- 질문: `next`의 경우 css를 어떻게 적용하나요?
  - css파일에서 스타일적용 방법
    - import styles from './styles.css';
  - 함수내에서 style.jsx를 추가해서 css적용(css-in-js  styled-jsx)
    - [참고 사이트1](https://brunch.co.kr/@hee072794/89)
    - [참고 사이트2](https://blog.woolta.com/categories/1/posts/185)

## 🐾  정아

- 테이블을 어떻게 만들지 고민해봤습니다.
  - [후보 1](https://codepen.io/lukepeters/pen/bfFur)
<p><img src="https://user-images.githubusercontent.com/55867479/85917963-ae2e5300-b899-11ea-8551-58ad2267fe68.png" width=500></p>
<p><img src="https://user-images.githubusercontent.com/55867479/85917975-c1d9b980-b899-11ea-8cb4-8d07ccaa6c69.png" width=500></p>

  - 후보2 : 헤더는 가만히 있고 화면이 줄어들었을 때 화면이 하나만 남게 만드는것
    - 의견: 2개가 남아도 괜찮을 것 같아요.
<p><img src="https://user-images.githubusercontent.com/55867479/85918020-0b2a0900-b89a-11ea-9c29-1561b9d5dcc0.png" width=200></p>

  - [후보3](https://codepen.io/ralphsaniatan/full/ZEGaqgw)  (미혜님 의견) : 개선의 여지가 있지만 이런 스타일도 한번 참고해보면 좋을것 같습니다.
<p><img src="https://user-images.githubusercontent.com/55867479/85918013-05342800-b89a-11ea-92b8-b479c901616e.png" width=700></p>

<p><img src="https://user-images.githubusercontent.com/55867479/85918004-ef266780-b899-11ea-9881-f3c969b8311b.png" width=400></p>

**Comment by kirrikirri42** [comment]
중간점검 로그 감사합니다!

**Comment by SeongsangCHO** [comment]
로그정리 감사합니다 ㅎㅎ

제 고민 1번에 대해서는 방금 강의를 보면서 어느정도 맥락을 잡았습니다.

https://www.youtube.com/watch?v=WzE08kNG4mg

앞 부분은 Next관련 환경설정이고 14분부터 참고하시면 될듯한데,

태리님께서 말씀하신 express 서버쪽에서 라우팅을 /api/.. 라고 하셨던 것에서 참고하여 조금 정리해보겠습니다.

해당 강의 코드는 웹 api에서 JSON데이터를 불러오는 것 같습니다.
('https://api.tvmaze.....')으로 fecth함수를 통해 백엔드서버와 비동기통신을 진행하여, 원하는 데이터를 추출해 화면에 뿌려주는 예제같습니다.

그래서 해당 예제에서 통신하는 api는 우리 프로젝트에선 백엔드서버가 될 것 같고 next에서 예제처럼 진행하면 express와 nextJS가 적용된 react APP에서 통신이 가능할 것 같습니다.

**Comment by taelee42** [comment]
> 리액트에서 작성한 JS파일들을 build해서 이 정적파일자체를 배포하는 것을 찾아봐야할것 같습니다.
저도 제일 알고싶은 부분이 이부분입니다!!

동영상을 잘봤습니다. fetch로 비동기로 api에서 가져오는군요!! 감사합니다. 
백, 프론트 연결할때 적용해 보겠습니다.

**Comment by SeongsangCHO** [comment]
https://okky.kr/article/706282 <- 글을 보고.. 생각난건데
SERVER에서 PUBLIC에는 서버에 올라갈 파일만 넣어야한다. 라는 문구를 어디서 봤었습니다.
정적파일을 SERVER의 PUBLIC에 넣어야하는지? 라는 궁금증이 생기네욤 ㅇㅅㅇ
