### ISSUE TITLE
Confirming Color Scheme

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#26]
Here are the Hex color codes, according to the results of the final vote
__Primary__ (60%) : #589CFA
__Second__ (30%) : (@kirrikirri42 knows...)
__Accent__ (10%) : (@kirrikirri42 knows...)

This will be applied to all components until the next vote!

---
지난 마지막 투표때 결정된 색상코드 입니다.
다음 투표 전까지는 이 색상코드로 각 컴포넌트에 적용하겠습니다.

![슬라이드13](https://user-images.githubusercontent.com/60066472/86261256-48bfc680-bbf9-11ea-924c-6896d94209f1.PNG)

**Comment by hidaehyunlee** [comment]
푸릇한 예발자를 위한 색 조아연

**Comment by kirrikirri42** [comment]
색 고르는 방법을 통해 구성해본 색상은 아래와 같습니다
Primary (60%) : #589CFA
Second (30%) : #F2F8FF
Accent (10%) : #4DF0FF
![image](https://user-images.githubusercontent.com/52592748/86318669-85c5a080-bc6d-11ea-89d2-dbd381407c4a.png)
