### ISSUE TITLE
Design Database and Build a Website Server

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#3]
__To do__
- Each member makes one's own code.
    - [x] Design database _(based on the shared idea at today's meeting)_ and Implement it
    - [x] Build a website server
- The best one will be merged after code review on 6/15(Mon) @10am

---
__해야할 일__
- 필요한 지식을 학습하고 각자 코드를 작성합니다
    - 데이터베이스 설계 및 구현 _(오늘 미팅 내용 토대로)_
    - 웹서버 구현
- 6/15(월) @10am 에 코드리뷰 후 가장 좋은 안으로 진행합니다.

**Comment by taelee42** [comment]
잘 확인했습니다.
다음주까지 열심히 공부해 가겠습니다!
