### ISSUE TITLE
Need to confirm contents of FAQ and About

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#31]
Please write down what you want to insert on the FAQ page.
ex) what is BOOTCAMP?
- BOOTCAMP is ~~...
---

FAQ, About에 들어갈 내용을 생각나는대로 적어주세요~!
예시) 부트캠프는 뭔가요?
부트캠프는 ...

**Comment by 365kim** [comment]
- https://42seoul.kr/faq
- https://www.ssafy.com/ksp/servlet/swp.faq.controller.SwpFaqServlet
- http://boostcamp.connect.or.kr/faq.html
- https://woowacourse.github.io/faq.html
- http://swmaestro.org/web/board/boardContentsListPage.do?board_id=27

스마일 서버개발캠프, 멋쟁이 사자처럼은 부트캠프 공식홈페이지라고 부를만한게 없어서(또는 찾지못해서) 없었는데
나머지 사이트에서는 모두 faq를 게시하고 있었습니다.

**Comment by 365kim** [comment]
About에는
- 저희 다섯명소개
- 개발하게 된 계기, 취지
- 개발 히스토리 간략하게
소개하면 좋을 것 같습니다!
