### ISSUE TITLE
[Dev_log] 9 July (Tue)

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#35]
## 🐾1. Done
- Seperated work area of Front-End and Back-End __(#28)__
    - Added function of adding data in localhost
    - Implemented admin page for on yebalja.com/db
    - Created database for implementing Yearly Calendar
- Adopted Nextjs __(#29)__
- Implemented 'Home' page __(#30, #33)__
<br>

## 🐾2. Learned
- __How to solve the error below__ <p><img width="426" alt="error" src="https://user-images.githubusercontent.com/60066472/87043843-a9ba5080-c230-11ea-80e1-a06fe0899393.png"></p>
     - wrap with \<thead\> tag
- __Call to Action__
    - a piece of content intended to induce a viewer, reader, or listener to perform a specific act, typically taking the form of an instruction or directive (e.g. buy now or click here ).
- __Cross-Origin Resource Sharing__
    - a mechanism that allows restricted resources on a web page to be requested from another domain outside the domain from which the first resource was served
- __Google Analytics__
- __How to use `git rebase`__
<br>

## 🐾3. Decided
- Defined the [color scheme](https://github.com/FiveEat42/yebalja.com/wiki/Color-Scheme) & how to apply the color scheme
- Detailed design of Navbar, Jumbotron, Yearly Calendar, and Footer
- Drafted 'Detail' page
- Planned to do research and verify on each bootcamp
<br>

## 🐾4. To do
- To finish implementing 'Home' page. 
- To draft 'Detail' page.
- To implement login function.
<br>
---

## 🐾 1차 배포까지 D-10
- [전체일정보기](https://docs.google.com/spreadsheets/d/1wWLF3vMi655IZUV0sBrItizn24Pd0nGPDffO9lTlEqY/edit#gid=136791574)
<br>

## 🐾 완료
- 프론트/백 작업공간 구분 완료 __(#28)__
    - localhost에서 자료입력 기능 추가 완료
    - yebalja.com/db의 관리(admin) 페이지 구현 완료
    - 연간일정 구현에 필요한 db 구현 완료
- 프론트 넥스트 적용 완료 __(#29)__
- 홈화면 - 헤더, 점보트론, 표, 푸터 구현 완료 __(#30, #33)__

<br>

## 🐾 새로 배운 것
- __테이블 관련 에러 해결방법__
    - \<thead\>로 감싸준다
- __CTA__ _(Call to Action)_
    - 사용자의 반응을 유도하는 행위 혹은 요소
    - 웹사이트에서 우리가 흔히 보는 ‘배너’, ‘버튼’, ‘링크’ 등
- __CORS__ _(Cross-Origin Resource Sharing)_
    - 다른 오리진(서버)간의 리소스 쉐어링
    - 원래 REST 요청 (get, post등)은 같은 서버에서만 가능함.
    - 프론트(3000포트)서버와 백(5000포트)서버도 포트가 달라서 다른 서버로 인식하므로 CORS에 의해 서로 요청을 받아줄 수 없는 것임.
    - 이때 '프록시'가 중간에 껴서 프론트에서 오는 요청을 마치 백에서 보낸 요청처럼 바꿔주는 역할을 해줌
- __구글애널리틱스__ _(google analytics)_
    - 방문자 통계, 방문 경로 등 집계 가능
- 깃 리베이스 (git rebase)
    - git rebase [사용 방법](https://velog.io/@taelee/git-rebase-%EC%8B%9C%EB%8F%84-%ED%9B%84-%EC%84%B1%EA%B3%B5-5E)
 <br>

## 🐾 같이 결정한 것
- __홈화면__
    - 전체적으로 톤 정리 ([__컬러스킴__](https://github.com/FiveEat42/yebalja.com/wiki/Color-Scheme) 참조)
    - 내비바
        - 점보트론과 분리하여 그림자있게 추가
        - 각 부트캠프가 내비 아이템이 되도록 변경 (faq는 삭제)
        - 햄버거는 나중에 오른쪽으로 이동 검토
    - 연간일정
        - 모바일 화면에서는 숨기는 것으로 정리
        - 나중에 스크롤 추가해서 살리는 것 검토
        - '멋사'는 정해진 연간일정 넣기 (e.g. 2~3월 모집 / 해커톤 등)
        - '우테코'는 ~예정이라고 넣고 공지뜨면 업데이트
        - 라피신(42)/챌린지(부캠)의 경우 둘 다 1개월인데 선발/교육시작으로 다르게 구분하기 모호하므로 '라피신' '챌린지' 로 표기
        - 가능하다면 CTA 넣기
    - 푸터
        - 점 빼고, 카피라이트 맨 아래로, 반응형일 떄 왼쪽정렬되도록 정리
- __상세화면__
    - 레이아웃
        - 타이틀 > 1줄설명 > 타임라인 > faq추린정보 > faq링크+리뷰링크 순으로 정렬
    - 자료조사 계획
        - 태혁(42), 대현(멋사), 미혜(싸피,우테코), 정아(부캠), 세초(소마)
        - 조사양식 : [__스프레드시트__](https://docs.google.com/spreadsheets/d/1HzeNsseeoNE3VePtvFmXs99p_PDSaeSuSPYIwcjzX9o/edit#gid=0) 에 필요한대로 추가
        - 조사대상
            - 괜찮은 후기 5개 내외 링크찾기
            - 소개글 1줄(대현's 타임라인 참조)
            - 엑셀표에 있는 일정 크로스체크(최대한 세분화)
            - 특이사항 (e.g. 싸피는 지역별로 뽑는다, 소마는 개발비를 준다, 라피신 설명 등)
    - 컴포넌트 구현(윤곽잡기)
        - 우선 42서울 기준으로 1개 구현
        - 타임라인(정아) , faq 기반 자세한 설명(미혜), 리뷰링크(대현)
        - faq 기반 설명은 1개 
        - 리뷰링크는 맛집소개st로 도전
<br>

## 🐾 할 일
- __7/9 (목) 까지__
    - [x] feature/home 풀리퀘 리뷰완료 `taelee`, `secho`
    - [x] yearlyCalendar 풀리퀘 `daelee`
    - [x] 컬러스킴 위키에 추가 `jehong`
- __7/10(금) 까지__
    - [x] yearlyCalendar 풀리퀘 리뷰완료  `taelee`, `secho`, `jehong`, `mihykim`
- __7/12(일) 까지__
    - [x] navbar 추가 정리끝 `mihykim` 
    - [x] footer 정렬, 서식변경 정리끝  후 풀리퀘 `mihykim` 
    - [x] jumbotron  텍스트위치, svg 애니메이션 조정 `jehong`
    - [x] table 색상, 너비조정  후 풀리퀘 `jehong`
    - [x] yearly 색상, 가능하면 CTA 추가 `daelee`
- __7/14(화) 까지__
    - [ ] 상세화면 layout 잡기 `mihykim`
    - [ ] 상세화면 faq 기반 상세설명 후 풀리퀘 `mihykim`
    - [ ] 상세화면 타임라인 후 풀리퀘 `jehong`
    - [ ] 상세화면 리뷰링크모음 후 풀리퀘 `daelee`
    - [x] 로그인에 필요한 테이블 구성 `taelee`, `secho`
    - [x] 암호화를 위해 bcrypt미들웨어 사용 `taelee`, `secho`
    - [x] 멤버 정보들을 받는 입력페이지 구성 `taelee`, `secho`
    - [x] ID와 PW를 입력받는 로그인 페이지 구성 `taelee`, `secho`
    - [x] 서버가 실행되는 동안 유지되는 웹토큰 학습 및 구현 `taelee`, `secho`
    - [ ] https 인증서 발급받아서 구현하기 `taelee`, `secho`
    - [x] 42서울 자료조사 `taelee`
    - [x] 멋사 자료조사 `daelee`
    - [x] 부스트캠프 자료조사 `jehong`
    - [x] 소프트웨어 마에스트로 자료조사 `secho`
    - [x] 싸피 자료조사  `mihykim`
    - [x] 우테코 자료조사  `mihykim`
- __7/14(화) 오후 4시 회의 안건__
    - 자료조사한 것 확인 후 구현한 컴포넌트에 활용
    - About 페이지 내용 구성
    - 백에서 프론트로 전달받을 데이터 형식 확정 등

**Comment by kirrikirri42** [comment]
빠르고 깔끔한 정리 감사합니다!
풀리퀘, 스프레드시트 등등 링크 달아주셔서 넘 좋네요
할 일도 세부적으로 나눠지고 담당자 이름도 태그돼서 보기 편하고 좋습니다

**Comment by hidaehyunlee** [comment]
투두리스트 정리 넘 감사합니다. 참고해서 진행하겠슴니다😊😊

**Comment by SeongsangCHO** [comment]
투두리스트 너무 좋아요 감사합니다

**Comment by taelee42** [comment]
투두 리스트가 정리되니 퀘스트 깨는거 같아서 너무 좋네요.
퀘스트 마저 완료하러 가겠습니다!!
