### ISSUE TITLE
Need to specify the data format to receive from BE to FE

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#37]
We have to specify the data format to receive from the front-end.
We should also learn about redux and how to manage and receive data.

---

FE쪽에서 받을 데이터포맷을 정해야합니다.
그리고 REDUX에 대해 학습하고 데이터를 관리 및 받는 방법을 배워야합니다!

**Comment by 365kim** [comment]
Let's do it on Tuesday

**Comment by 365kim** [comment]
컴포넌트 별 필요한 데이터 목록

### Home
- Yearly Calendar `daelee`
    - 날짜 : Date형식
- Table `jehong`
    - 프로그램 : String 형식 (e.g. 42서울)
    - 코딩테스트 : String 형식 (e.g. O)

### Detail
- Timeline `jehong`
- Info `mihykim`
    - 프로그램 : String 형식 (e.g. 42서울)
    - 질문 목록
    - 답변 목록
- Review  `daelee`
    - 프로그램
    - 링크 제목
    - 링크 주소

**Comment by 365kim** [comment]
### DETAIL
- Timeline `jehong`
    - 지원/선발/사전집중교육/교육시작 중 '교육시작'에 해당하는지 구분 필요
    - "step-name" : String 형식  (연간일정/타임라인 겸용 )
        - 지원/선발/사전집중교육/교육시작 중 '교육시작'에 해당하는지 구분해주는 변수
    - "step_summary" : String 형식  (연간일정/타임라인 겸용 )
    - 시작날짜, 종료날짜 : String 형식
    - 디데이 : String 형식
- Info `mihykim`
    - 프로그램 : String 형식 (e.g. 42서울)
    - 해당프로그램 질문/답변 목록 :  String 형식 
- Review  `daelee`
    - 프로그램 : String 형식 (e.g. 42서울)
    - 링크 url : String형식?
    - 조금 더 구현해보고 다시 정하기
