### ISSUE TITLE
Need to implement detail page

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#41]
We need to implement Detail pages for each bootcamp.
- [x] Implement Horizontal Timeline `jehong`
- [x] Implement Detailed Explanation `mihykim`
- [x] Implement List of Links to Reviews `daelee`

**Comment by hidaehyunlee** [comment]
Inspiration for Menu Hover Effects
[Demo](https://tympanus.net/Development/MenuHoverEffects/#)
- Demo

**Comment by 365kim** [comment]
Keyword `Text Scroll`, `Rolling Text`
https://codepen.io/baltazarparra/pen/oLKpwb
https://codepen.io/roychan/pen/avrVJP
https://codepen.io/hajaran/pen/BmbJLz

**Comment by 365kim** [comment]
Keyword FAQ
https://codepen.io/moso/pen/vKGxMx
