### ISSUE TITLE
Need to change DNS ip

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#49]
Need to change DNS ip to http://34.64.205.88/

Server spec is not enough now so I add instance for front-end.

I had to get the certificate again, but an error occurred.
I think it was caused by not changing the DNS IP.

---

현재 DNS IP를 http://34.64.205.88/로 변경해주세요

서버 스펙이 좋지 않아서 터지고 있습니다.. 
프론트서버, 백 서버를 각각 구동하기 위해
 서버 스펙을 올리고 인스턴스를 다시 만들었습니다.

새로운 인스턴스에서 배포는 잘되는데, 인증서를 다시 발급받으려하니 에러가 발생했습니다
아마 DNS IP를 변경하지 않아서 그런 것 같은데.. 제발 그랬으면 좋겠습니다.

**Comment by 365kim** [comment]
헉-

**Comment by SeongsangCHO** [comment]
해결스
