### ISSUE TITLE
To create a high-quality site

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#56]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/37580034/87998791-e8ef7800-cb33-11ea-9e87-cb3754761938.png">

- Need to add a `Favicon`
- Need to modify the representative phrases shown when we search `yebalja.com` on Google.
---
- 우리 사이트에 파비콘을 추가해야합니다.
- `예발자닷컴`을 구글링했을 때 노출되는 대표문구를 수정하고 싶습니다!

**Comment by kirrikirri42** [comment]
파비콘!!!

**Comment by 365kim** [comment]
### 심플1
![fav1](https://user-images.githubusercontent.com/60066472/88016924-80b68b80-cb5f-11ea-88c3-4be90ee64f64.PNG)

### 심플2
![fav2](https://user-images.githubusercontent.com/60066472/88016930-83b17c00-cb5f-11ea-85ea-6759923dd371.PNG)

**Comment by hidaehyunlee** [comment]
`시작`, `안내`, `길잡이`, `목표`, `목적`, `진화`, `미래` 
요런 키워드가 담긴 상징적인 로고가 있으면 좋을 것 같아요.

예를 들면 프로그래머스는 새, 인프런은 나뭇잎 이런식으로 딱 떠오르는 아이콘이 있고, 아이콘을 파비콘으로 사용하고 있더라구요.

떠오르는 이미지는...

- 새싹

![image](https://user-images.githubusercontent.com/37580034/88302061-5a9c1180-cd40-11ea-9858-e9acae6c0d1b.png)

- 로켓(우주선)
![](https://freedesignfile.com/upload/2017/08/rocket-icon-vector.png)
- 나침반
![image](https://user-images.githubusercontent.com/37580034/88302162-7bfcfd80-cd40-11ea-899a-7d6777f6b7c3.png)


- 네비게이터 (화살표)
![image](https://user-images.githubusercontent.com/37580034/88302328-b070b980-cd40-11ea-813e-88b7264641d5.jpeg)

![image](https://user-images.githubusercontent.com/37580034/88302405-c7171080-cd40-11ea-9f2e-a2687fee0e22.jpeg)
![image](https://user-images.githubusercontent.com/37580034/88302408-c8483d80-cd40-11ea-8d61-7d4a3b4e90a9.png)



- 은하수를 여행하는 히치하이커를 위한 안내서


![image](https://user-images.githubusercontent.com/37580034/88302654-12312380-cd41-11ea-89a3-bded2cedc34c.jpeg)

- 진화

![image](https://user-images.githubusercontent.com/37580034/88303008-7c49c880-cd41-11ea-9e6a-d2ec05ce71bd.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89268686-d61c8d80-d673-11ea-9e2f-d6710ed17e95.png)
성상님이 만드신 Y 입니다
그렇게 안 보일 수도 있는데 하트 모양 클로버잎 다섯 장을 떼다 만드신 의미있는 작품이랍니다

**Comment by kirrikirri42** [comment]
Y1 투명
![image](https://user-images.githubusercontent.com/52592748/89286000-65359f80-d68c-11ea-9115-e5a884f6d579.png)
Y2 흰배경
![image](https://user-images.githubusercontent.com/52592748/89286026-7088cb00-d68c-11ea-9f74-69e8a594b4a7.png)
Y3 푸른배경
![image](https://user-images.githubusercontent.com/52592748/89286038-77afd900-d68c-11ea-96e0-dd1eb6844ca9.png)


blue sprout 1
![image](https://user-images.githubusercontent.com/52592748/89286071-872f2200-d68c-11ea-9254-022529652c5e.png)

blue sprout 2
![image](https://user-images.githubusercontent.com/52592748/89286093-901ff380-d68c-11ea-8b40-d06be19d8216.png)

뱃지2
![image](https://user-images.githubusercontent.com/52592748/89286150-a9c13b00-d68c-11ea-8d6f-3ddce668139c.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89371099-50edb300-d71d-11ea-937c-b9b317046b8d.png)
![image](https://user-images.githubusercontent.com/52592748/89371110-59de8480-d71d-11ea-90b4-e24f7d7511bd.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89371171-84304200-d71d-11ea-8424-947d84526b42.png)
![image](https://user-images.githubusercontent.com/52592748/89371178-8abeb980-d71d-11ea-8394-b8ee031fe632.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89371248-cce7fb00-d71d-11ea-8a8f-12d880ad5070.png)
![image](https://user-images.githubusercontent.com/52592748/89371260-d40f0900-d71d-11ea-8ea1-88728db494e2.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89371906-9f9c4c80-d71f-11ea-9115-40a1ea92eac5.png)
![image](https://user-images.githubusercontent.com/52592748/89371919-a88d1e00-d71f-11ea-9729-4c3c7b72a09a.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89372012-ee49e680-d71f-11ea-9a3f-ef581e2b2436.png)
![image](https://user-images.githubusercontent.com/52592748/89372026-f6098b00-d71f-11ea-9df4-c50405550de0.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89375572-e9d5fb80-d728-11ea-93c8-08035d8fd889.png)
![image](https://user-images.githubusercontent.com/52592748/89375717-2f92c400-d729-11ea-8d14-110d8f74b2c2.png)

**Comment by kirrikirri42** [comment]
새싹 파비콘에 떡잎 로고가 좋다는 의견이 많습니다


![image](https://user-images.githubusercontent.com/52592748/89377126-222b0900-d72c-11ea-80c0-d4b56b3433e9.png)



![image](https://user-images.githubusercontent.com/52592748/89377076-0a538500-d72c-11ea-941d-6be2d62bc1a9.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89502248-aac6a980-d7ff-11ea-94f1-bae7be88b50f.png)
![image](https://user-images.githubusercontent.com/52592748/89502717-62f45200-d800-11ea-8743-34837092eb68.png)
![image](https://user-images.githubusercontent.com/52592748/89502784-7e5f5d00-d800-11ea-8448-46cc05a4e6d5.png)
![image](https://user-images.githubusercontent.com/52592748/89503018-e7df6b80-d800-11ea-85c0-5adaae2b1b0c.png)
![image](https://user-images.githubusercontent.com/52592748/89502982-d8f8b900-d800-11ea-95e8-4834418429ec.png)

상추..??

**Comment by 365kim** [comment]
![image](https://user-images.githubusercontent.com/60066472/89557722-38c98100-d84e-11ea-9287-d95e463f045a.png)
저의 요청에 정아님께서 작업해주셨습니당-! 감사합니당!!

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/89610173-d5bf0500-d8b4-11ea-971e-08b40a29d174.png)
비대칭 흑백버전도 만들어봤습니닷

**Comment by kirrikirri42** [comment]
실패작들이지만 뭔가 아쉬워서 올려봅니당

![image](https://user-images.githubusercontent.com/52592748/89610297-1a4aa080-d8b5-11ea-89eb-fd45b363a1f9.png)
![image](https://user-images.githubusercontent.com/52592748/89610346-38180580-d8b5-11ea-9325-381b9ed343e3.png)
![image](https://user-images.githubusercontent.com/52592748/89610418-65fd4a00-d8b5-11ea-980f-fd0bd06003a1.png)
![image](https://user-images.githubusercontent.com/52592748/89610509-a65cc800-d8b5-11ea-9438-7d88c4b91027.png)
![image](https://user-images.githubusercontent.com/52592748/89610552-c2606980-d8b5-11ea-8c61-c32f92274543.png)
![image](https://user-images.githubusercontent.com/52592748/89610694-2be07800-d8b6-11ea-8bf4-373847c2a979.png)
![image](https://user-images.githubusercontent.com/52592748/89610950-d48ed780-d8b6-11ea-879b-a4e4de6a4d63.png)
![image](https://user-images.githubusercontent.com/52592748/89611579-8bd81e00-d8b8-11ea-9e90-31bb73dc0ee1.png)
![image](https://user-images.githubusercontent.com/52592748/89611796-0739cf80-d8b9-11ea-95d2-f2137d548c22.png)
![image](https://user-images.githubusercontent.com/52592748/89612451-ca6ed800-d8ba-11ea-90a6-60adca8591a4.png)

**Comment by kirrikirri42** [comment]
1. ![image](https://user-images.githubusercontent.com/52592748/88018685-2c150f80-cb63-11ea-93ca-5688e6e560e5.png)

2. ![image](https://user-images.githubusercontent.com/52592748/88018727-44852a00-cb63-11ea-929f-7210d8b4fdce.png)

3. ![image](https://user-images.githubusercontent.com/52592748/88019088-ea389900-cb63-11ea-8037-93240a380287.png)

4. ![fav1](https://user-images.githubusercontent.com/60066472/88016924-80b68b80-cb5f-11ea-88c3-4be90ee64f64.PNG)

5. ![fav2](https://user-images.githubusercontent.com/60066472/88016930-83b17c00-cb5f-11ea-85ea-6759923dd371.PNG)

6. ![image](https://user-images.githubusercontent.com/52592748/89268843-0bc17680-d674-11ea-9aeb-96fc9439add4.png)

7. ![image](https://user-images.githubusercontent.com/52592748/89286000-65359f80-d68c-11ea-9115-e5a884f6d579.png)

8. ![image](https://user-images.githubusercontent.com/52592748/89286026-7088cb00-d68c-11ea-9f74-69e8a594b4a7.png)

9. ![image](https://user-images.githubusercontent.com/52592748/89286038-77afd900-d68c-11ea-96e0-dd1eb6844ca9.png)

10. ![image](https://user-images.githubusercontent.com/52592748/89286071-872f2200-d68c-11ea-9254-022529652c5e.png)

11. ![image](https://user-images.githubusercontent.com/52592748/89286093-901ff380-d68c-11ea-8b40-d06be19d8216.png)

12. ![image](https://user-images.githubusercontent.com/52592748/89286150-a9c13b00-d68c-11ea-8d6f-3ddce668139c.png)

13. ![image](https://user-images.githubusercontent.com/52592748/89372416-1259f780-d721-11ea-8324-837a4692e67e.png)

14. ![image](https://user-images.githubusercontent.com/52592748/89375572-e9d5fb80-d728-11ea-93c8-08035d8fd889.png)

15. ![image](https://user-images.githubusercontent.com/52592748/89378726-6bc92300-d72f-11ea-8b65-48550167ae2a.png)

16. ![image](https://user-images.githubusercontent.com/52592748/89378748-797ea880-d72f-11ea-98cd-4a4334245fec.png)

17. ![image](https://user-images.githubusercontent.com/52592748/89502248-aac6a980-d7ff-11ea-94f1-bae7be88b50f.png)

18. ![image](https://user-images.githubusercontent.com/52592748/89502717-62f45200-d800-11ea-8743-34837092eb68.png)

19. ![image](https://user-images.githubusercontent.com/52592748/89502784-7e5f5d00-d800-11ea-8448-46cc05a4e6d5.png)

20. ![image](https://user-images.githubusercontent.com/60066472/89557722-38c98100-d84e-11ea-9287-d95e463f045a.png)

21. ![image](https://user-images.githubusercontent.com/52592748/89610173-d5bf0500-d8b4-11ea-971e-08b40a29d174.png)

22. ![image](https://user-images.githubusercontent.com/52592748/89610297-1a4aa080-d8b5-11ea-89eb-fd45b363a1f9.png)

23. ![image](https://user-images.githubusercontent.com/52592748/89610346-38180580-d8b5-11ea-9325-381b9ed343e3.png)

24. ![image](https://user-images.githubusercontent.com/52592748/89610418-65fd4a00-d8b5-11ea-980f-fd0bd06003a1.png)

25. ![image](https://user-images.githubusercontent.com/52592748/89610509-a65cc800-d8b5-11ea-9438-7d88c4b91027.png)

26. ![image](https://user-images.githubusercontent.com/52592748/89610552-c2606980-d8b5-11ea-8c61-c32f92274543.png)

27. ![image](https://user-images.githubusercontent.com/52592748/89610694-2be07800-d8b6-11ea-8bf4-373847c2a979.png)

28. ![image](https://user-images.githubusercontent.com/52592748/89610950-d48ed780-d8b6-11ea-879b-a4e4de6a4d63.png)

29. ![image](https://user-images.githubusercontent.com/52592748/89611579-8bd81e00-d8b8-11ea-9e90-31bb73dc0ee1.png)

30. ![image](https://user-images.githubusercontent.com/52592748/89611796-0739cf80-d8b9-11ea-95d2-f2137d548c22.png)

31. ![image](https://user-images.githubusercontent.com/52592748/89612451-ca6ed800-d8ba-11ea-90a6-60adca8591a4.png)

**Comment by kirrikirri42** [comment]
![image](https://user-images.githubusercontent.com/52592748/90336104-88f5cf80-e014-11ea-802e-6db4d1f4a8ab.png)
새로운 파비콘으로 정해졌습니다
