### ISSUE TITLE
Need to implement 'About' page

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#59]
We need to implement 'About' page.
Let's start from drafting the design.
What kinds of components would be needed?

---
어바웃 페이지를 공략해봅시당!!
우선 초안을 함께 짜보면 좋을 것 같아요!
어떤 컴포넌트가 필요할까요?

**Comment by kirrikirri42** [comment]
- [인프런](https://www.inflearn.com/inflearn)처럼 점보트론이 들어가면 좋을 것 같습니다
  - 개인적으로 여기에 미혜님의 일러스트가 들어가도 좋을 것 같습니다
![image](https://user-images.githubusercontent.com/52592748/88124520-4a811680-cc08-11ea-8353-c29cc2008f30.png)

- 예발자 팀원들의 소개와 각자의 깃헙이나 블로그 링크가 있으면 좋을 것 같습니다. [코드펜](https://codepen.io/about/)
![image](https://user-images.githubusercontent.com/52592748/88124714-b5325200-cc08-11ea-8d48-2e39b9b47808.png)

- 대리님이 의견주셨던 것처럼 [눈누](https://noonnu.cc/about)를 참고해 저희도 커피 한 잔을 어필해보면 어떨까요
![image](https://user-images.githubusercontent.com/52592748/88124772-d8f59800-cc08-11ea-82eb-c7af95bf8fd9.png)

**Comment by 365kim** [comment]
- 비포
![draft_il](https://user-images.githubusercontent.com/60066472/88354284-5d782000-cd9b-11ea-8ae8-d2c19d4e6b0d.jpg)
- 애프터
will appear soon....

**Comment by 365kim** [comment]
- 스크롤 부드럽게 내려가는 코드
https://codepen.io/clo-schorderet/pen/yLBwogZ

**Comment by 365kim** [comment]
- !!반응형!! 다이아몬드 팀원 소개
https://codepen.io/thenahid/pen/WXKONJ?editors=1010

**Comment by hidaehyunlee** [comment]
프로필 업로드요 이미지 입니다.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/37580034/88367073-cd9b9b80-cdc5-11ea-8056-b522189f858d.png">

**Comment by 365kim** [comment]
- 개인별 정보
1. 이름
2. back end
3. 깃헙링크
4. 벨로그링크

- 커피후원링크
