### ISSUE TITLE
[Dev_log] 23 July (Thu)

### ISSUE THREAD

**Issue by hidaehyunlee** [FiveEat42/yebalja.com#62]
#### Front

- nav 아이템 클릭했을 때 누른 표시가 나도록 active 클래스를 적용했습니다.
- home/YearlyCalendar 톤을 정리했습니다.
- home/Table 컬럼을 간소화하고 뱃지를 추가했습니다.
- 우측 하단에 최상단 바로가기 버튼을 추가했습니다.
- 디테일 페이지에 들어갈 컴포넌트 완성했습니다. 개선이 필요합니다.

#### Back

- GCP상에서 npm 명령어로 build되지 않는 이슈를 해결했습니다.

- pm2로 유지시켜주는 빌드를 `npm run dev`에서 `.next` 정적파일로 변경했습니다.

  - **브라우저에 빌드**를 맡기는 npm run dev 방식은 속도가 느리기 때문에 사실 좋은 배포 방식이 아니었음.
  -  `.next`를 배포할 때는 **서버에서 빌드**를 먼저 하고 웹에서는 정적파일을 받아와서 보여주기만 하기 때문에 속도가 훨씬 빠름.
    1. `next build` 
    2. `.next` 에 빌드된 정적파일 생성 
    3. `next start` 로 배포

  -> 진정한 **서버사이드렌더링(SSR)**

- admin 페이지 로그아웃 기능을 구현했습니다.

- `.env` 패키지를 이용해 보안관련 정보 관리합니다.

  - `nginx`를 이용해 http로 접속해도 https로 redirect 되도록 설정했습니다.
  - `443`으로 접속해도 자동으로 `80`으로 접속되게해줌
  - 즉, `443`/`80` 모두 내부적으로 `3000`/`5000`번 포트로 돌려줌

- **back + DB**(5000포트 > api.yebalja.com) 서버와 **front** 서버(3000포트 > www.yebalja.com)를 나눴습니다.

  - 리소스 절약을 위해.
  - 서버가 다운되었을 때 대처하기 위해.

------

## 🐾 2. 배웠습니다.

- 게이트웨이 : app.use() 

  - 게이트웨이(익스프레스)가 미들웨어(비크립트)

- 포트 : 컴퓨터마다 6만5천개의 포트가 있고, 그 중 몇몇 포트는 이미 용도가 약속외어 있다. 포트가 없으면 한 컴퓨터에서 단 하나의 서버밖에 못 만든다.

  - `80포트` : http 웹서버의 기본 포트
  - `443포트` : https (ssl) 

- 

- SSL 인증서

  - http는 누구나 볼 수 있는 평문, https 는 암호화.

  - Let's Encryp라는 허가된 기관에서 무료로 싸게 3개월 단위로 지원.

  - 3개월 마다 갱신해야함. 아마 자동갱신도 가능할듯?

  - 한 도메인에 대해 공개키/비밀키가 존재. 공신력 있는 기관이 공개키를 가지고 있고, 도메인 주인이 인증서와 비밀키를 갖게 됨. 

  -  서로의 공개키와 비밀키로 암호화/복호화를 함.

    > 서버가 평문을 비밀키로 암호화
    > 기관이 공개키로 복호화 가능
    >
    > 기관이 공개키로 암호화
    > 서버가 비밀키로 복호화 가능

------

## 🐾 3. 결정했습니다.

- 오픈일 결정 : 8월 8일
  - slack에 홍보 

------

## 🐾 4. 고민입니다.

- footer 내용 정리가 필요합니다.
  - email 삭제
  - 추후 github icon 추가
- 프로젝트 회고록 정리해서 42에서 공유.
  - 공유 방식은 추후 고민
- back에서 data를 최초 한번만 받아오면 되는건지, 아니면 각 페이지에서 사용할 때마다 받아와야하는건지 모르겠습니다.
  - 한 파일에서 전부 받아서 페이지마다 가공만 하면 좋을 것 같은데...
  - Redux 공부가 필요할 것 같습니다.

------

#### Front

- back 에서 데이터 받아와서 컴포넌트 출력
- top-button 클릭했을때 테두리 삭제

#### Back

- [x] `secho`, `taelee`: 빌드된 프론트 서버와 백간의 통신 (~Sat PM 12:00)
- [x] `taelee`: 백서버 최신화(~Thu PM 11:59)
- [x] `secho`, `taelee`: 프론트 리팩토링 알아보기
- [x] `secho`: 이삿짐 싸기 (~Sun PM 11:59)

-  배포자동화 (후순위)

#### 공통

- 토요일 아침 10시부터 다같이 Redux 공부

**Comment by kirrikirri42** [comment]
이삿짐 싸기라니ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
정리 감사합니다 ㅎㅎㅎ

**Comment by kirrikirri42** [comment]
200729에 회의를 한 관계로 새로운 이슈를 팝니다
