### ISSUE TITLE
Need to Complete Front-End Refactoring

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#65]
- Need to Complete Front-End Refactoring
    - Draft code : `seminar/seonpark`  branch
    - Set dummy data in format of sets of "key: value" in each component
    - Make it as a component if it's reusable
---
- 프론트엔드 리팩토링을 완성해야합니다
    - 코드 초안 : `seminar/seonpark` 브랜치에 올라가있음
    - 각 컴포넌트에 "key: value" 세트 형태의 더미데이터를 설정
    - 재사용성이 있는 부분 컴포넌트화

**Comment by 365kim** [comment]
JS객체사용[https://www.zerocho.com/category/JavaScript/post/572c6f759a5f1c4db2481ee3]

**Comment by hidaehyunlee** [comment]
# jsx 조건부렌더링

JSX 내부에서 조건부 렌더링을 할 때 보통 `삼항연산자` / `AND 연산자`를 사용한다.

`if문`을 사용하려면 `IIFE(즉시 실행 함수 표현)`을 사용해야해서 약간 복잡쓰. 

## **1. 삼항연산자**
삼항연산자는 true 일 때와 false 일 때 다른 경우를 보여주고자 할 때 사용한다.

```js
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div>
        {
          1 + 1 === 2 
            ? (<div>맞아요!</div>)
            : (<div>틀려요!</div>)
        }
      </div>
    );
  }
}

export default App;
```

## **2. AND연산자**
단순히 조건이 true 일 때만 보여주고, false 경우 아무것도 보여주고 싶지 않을 때 사용한다.

```js
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div>
        {
          1 + 1 === 2 && (<div>맞아요!</div>)
        }
      </div>
    );
  }
}

export default App;
```

## **3. if문**
가끔 복잡한 조건을 작성해야 할 때도 있다. 그러한 조건들은 웬만하면 JSX 밖에서 로직을 작성하는것이 좋다. 하지만, 꼭 JSX 내부에서 작성해야 한다면, 아래와 같이 `IIFE` 를 사용한다. ( if문 대신 switch문을 작성해도 된다)

```js
import React, { Component } from 'react';

class App extends Component {
  render() {
    const value = 1;
    return (
      <div>
        {
          (function() {
            if (value === 1) return (<div>하나</div>);
            if (value === 2) return (<div>둘</div>);
            if (value === 3) return (<div>셋</div>);
          })()
        }
      </div>
    );
  }
}

export default App;
```

위의 조건문은 다음과 같이 화살표 함수로 고쳐서 쓸 수도 있다.

```js
(() => {
  if (value === 1) return (<div>하나</div>);
  if (value === 2) return (<div>둘</div>);
  if (value === 3) return (<div>셋</div>);
})()
```

.
