### ISSUE TITLE
[Dev_log] 29 July (Wed)

### ISSUE THREAD

**Issue by kirrikirri42** [FiveEat42/yebalja.com#67]
# 200729 수 dev log

## 2.  :paw_prints:Learned
- Learned that it's possible to make nested object for structuring dummy data

## 3.  :paw_prints:Decided

- Decided to refer to `mihykim`'s dummy data when structuring dummy data

- Front-end and Back-end decided to work on dummy data together

- Decided to structure each component's dummy data instead of planning the whole structure in advance

#### Structuring the Database

- `taelee` Dummy data's nested structure is more complicated than expected so it seems better to put them in workbench right away
- `secho` It is possible to use a search feature  
  - Foreign key seems very useful

- `mihykim` Every component, program and category has a complex structure so we better figure out how to created the database 
- `mihykim` Creating database itself seems difficult even after dummy data is ready 

#### front refactoring

- Need to figure out how to position functions for the same component
  - Create a file for every sub-component vs Put them all in the same file
  - Child components are not used elsewhere to it seems better to put them in the same file
  - Checked that it works fine when sub-components are put in the same file and couldn't find any reason to separate them yet

- Import data once in the uppermost parent component vs import data several times as needed
  - `taelee` It's better to structure dummy data in the most effective way for components. 
  - `daelee` It seems alright to create dummy data in children components

#### 29 July Wednesday ~ 30 July Friday (Wed, Thur, Fri)
- **front refactoring**
  - [x] Navbar `mihykim`
  - [x] RollingText `mihykim`
  - [x] FAQ `mihykim`
  - [x] Timeline `jehong`
  - [x] Yearly Calendar `daelee`
  - [x] Review `daelee`
  - [x] Table `jehong`
- **Creating dummy data**
  - [x] Navbar `mihykim`
  - [x] RollingText `mihykim`
  - [x] FAQ `mihykim`
      - Boostcamp, 42Seoul, SSAFY, Woowa, Soma, Likelion
  - [x] Timeline `jehong`
  - [x] Yearly Calendar `daelee`
  - [x] Review `daelee`
  - [x] Table `jehong`
- **Applying Redux**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table

#### 1 August Saturday ~ 5 August Wednesady (Sat, Sun, Mon, Tue, Wed)
- **Creating DataBase**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table
- **Changing DB to json files**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table
- [x] Finishing About page
- [x] Choosing favicon
- [x] Choosing logo
- [ ] Deciding when and how to announce and promote Yebalja's launching

#### 6 August Thur ~ 8 August Saturday (Thur, Fri, Sat)

- [x] Changing RollingText animation `mihykim`
- [x] Displaying a list when RollingText is clicked `mihykim`
- [x] Finishing Yearly
- [x] Changing Yearly CTA's text to `자세히` `jehong`
- [ ] Modifying SEO search results

---

# 200729 수 dev log

## 2.  :paw_prints:배웠습니다.
- 더미데이타를 구성할 때 depth를 주어 nested 객체를 만들 수 있는 것을 배웠습니다. (이중 객체 구조)

## 3.  :paw_prints:결정했습니다.

- `mihykim` 님의 FAQ 더미데이타 방식을 참고해 더미데이타를 만들기로 했습니다

- 프론트와 백팀이 함께 컴포넌트 분리 및 더미데이타 작성을 하기로 했습니다
- 더미데이타의 전체 구조는 나중에 생각하고 컴포넌트별로 편한 구조를 먼저 짜기로 했습니다

#### DB 구상

- `taelee` 더미데이타가 생각보다 하위구조가 많아서 DB 입력을 바로 워크벤치에서 넣어버리는게 나을 것 같습니다
- `secho` 검색 기능을 넣으면 부캠만 보여주세요 했을 때 부캠 관련된 것만 띄워줄 수 있습니다
  - 대분류로 외래키 사용해서 쪼개고 연결짓기를 사용하면 좋을 것 같습니다

- `mihykim` 각 컴포넌트, 프로그램, 카테고리 별로 하위구조가 많아서 어떻게 구성할지 먼저 생각해봐야합니다
- `mihykim` 다 짜놓은 더미데이타를 DB에 넣으려면 또 효율적으로 묶어서 입력해야하는데 그게 쉽지않을 것 같습니다

#### front refactoring

- 같은 컴포넌트를 구성하는데 쓰이는 컴포넌트 함수들의 배치를 어떻게 할지 고민입니다
  - 컴포넌트별로 파일 만들기 vs 하나의 파일에 정리하기
  - 다른데서 안 쓰는 함수들이라 한 파일에 넣고싶은데 빼서도 한 번 해보고싶습니다
  - 한 파일에 넣어도 작동이 잘 되는 것을 함께 확인했고 아직까지 따로 뺄 이유를 찾지 못했습니다

- 최상위 컴포넌트에서 데이타 한 번 불러오기 vs 여러번
  - `taelee` 어디서든 불러올 수 있어서 큰 구조는 나중에 생각하고 컴포넌트 별로 편한대로 구성하는 것이 좋습니다
  - `daelee` 더미 데이타를 최상위 말고 중간중간 컴포넌트에서 만들어도 될 것 같습니다

#### 7월 29일 수요일 ~ 30일 금요일 (수목금)
- **front refactoring**
  - [x] Navbar `mihykim`
  - [x] RollingText `mihykim`
  - [x] FAQ `mihykim`
  - [x] Timeline `jehong`
  - [x] Yearly Calendar `daelee`
  - [x] Review `daelee`
  - [x] Table `jehong`
- **더미데이터 만들기**
  - [x] Navbar `mihykim`
  - [x] RollingText `mihykim`
  - [x] FAQ `mihykim`
      - 부스트캠프, 42서울, 싸피, 우테코, 소마, 멋사
  - [x] Timeline `jehong`
  - [x] Yearly Calendar `daelee`
  - [x] Review `daelee`
  - [x] Table `jehong`
- **리덕스 래퍼 설명 듣고 적용하기**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table

#### 8월 1일 토요일 ~ 5일 수요일 (토일월화수)
- **DB 만들기**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table
- **json 파일로 변환하기**
  - [x] Navbar
  - [x] RollingText
  - [x] FAQ
  - [x] Timeline
  - [x] Yearly Calendar
  - [x] Review
  - [x] Table
- [x] About 페이지 완성하기
- [x] favicon 정하기
- [x] 로고 정하기
- [ ] 홍보 언제 어떻게 할지 정하기

#### 8월 6일 목요일~ 8일 토요일 (목금토)

- [x] 롤링텍스트 순서 애니메이션 변경하기 `mihykim`
- [x] 롤링텍스트 누르면 리스트 보여주기 `mihykim`
- [x] 연간 타임라인 마무리
- [x] 연간 CTA 문구 자세히로 바꾸기 `jehong`
- [ ] SEO 검색문구 다듬기

**Comment by kirrikirri42** [comment]
더미데이터를 컴포넌트별로 만들기로 했습니다.
e.g. 타임라인 더미데이터 = { 42서울: [], SSAFY: [], 부스트캠프: [], 멋사: [], ... }

완성 후 연간과 타임라인처럼 데이터가 겹치는 컴포넌트들은 하나의 더미데이터로 합치기로 했습니다.

**Comment by 365kim** [comment]
왕~~~~ 깔끔한 정리 감사합니다!🌼
꼼꼼히 정리해주신 덕분에 리팩토링하고 DB정리하는 방향이 뚜렷해지는 것 같습니다!!!
