### ISSUE TITLE
[Dev_log] 09 June (Tue)

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#7]
### :paw_prints: THINKING

- Have to decide about painting the main page.
  - The default calendar standard is the YEARLY form.
- Have to establish guidelines on how to progress of project after DB, server development.
- Have to make a discussion for Dev Environment.

### :paw_prints: LEARNED

- Learned the roles and functions of Github elements while writing issues, pull-request, and kanban board.

### :paw_prints: DECIDED

- **Meeting**
  - Start : From 15 June 20, exception of weekend 
  - Time : 10:00 ~ 
  - Location: youthzone, Gaepo-dong, Gangnam-gu, Seoul 
  - Purpose : code review, conference

- **Establishing a wiki guideline**
  - Integrated management of links to sharing useful links page on the Wiki.
  - Write dev-logs in one document and manage them in order of date.
  - As a rule, issues, pull requests, and comments should be written in English. Wiki be written in English and Korean versions.
  - Automatic deletion is not performed to keep branches or delete them freely.

- **GitHub Cooperation environment setting**
  - Work process is managed by issue, pull request, and kanban board.
  - Established  [Git convention](https://github.com/4Eat42/yebalja.com/wiki/Conventions) through discussion.

- **Assigning roles**
  - taelee42 : Wrote our service introduction page.
  - 365kim : designed Wiki and page structure, gathered useful links.
  - hidaehyunlee: Wrote Git and code conventions. 
  - seongsangCHO : Wrote this dev-log.

- **To do**
  - Understand web, server and database.
    - NODE.JS lecture Learning
    - [node.JS](https://opentutorials.org/course/3332)
    - [node.JS express](https://opentutorials.org/course/3370)
    - Database lecture Learning
      - [mysql basics](https://opentutorials.org/course/3161)
      - [node.JS using mysql](https://opentutorials.org/course/3347)
    - (+) Additional learning links
      - [HTML](https://opentutorials.org/course/3084)
      - [CSS](https://opentutorials.org/course/3086)
      - [JS](https://opentutorials.org/course/3085)
  - Until the meeting (15 June (Mon), 5 tracks are implemented, and pull-requests are created.
  - Design while learning individual Database or for the page.
  - Server implementation and running server.
  - Let's write it from issue to pull request to get used to it!
    <br>
---
<br>

### :paw_prints:  고민중입니다

- 메인페이지 출력에 대하여 결정해야합니다. 
  - 기본은 연간을 기준으로 출력합니다.
- DB, 서버 구현 및 구동 개발 이후에는 어떻게 진행할지 가이드라인을 수립해야합니다.
- 개발환경에 대한 토의가 필요합니다.

### :paw_prints: 배웠습니다

- 이슈, 풀 리퀘스트, 칸반보드를 작성해보며 github 요소들의 기능과 역할을 알게되었습니다.

### :paw_prints: 결정했습니다

- **모임**
  - 모임시작 : 20.06.15(월)부터 주말 제외 
  - 모임시간 : 10:00 ~ 
  - 모임위치 : 개포동 무중력지대 
  - 모임목적 : 코드리뷰, 회의
- **위키관련 가이드 수립**
  - 공유할 링크를 위키의 useful links페이지로 통합 관리합니다.
  - 한 문서내에 회의록을 작성하고 최신 날짜 순으로  관리합니다.
  - 이슈, 풀리퀘스트, 코멘트는 영문작성을 원칙으로하고 위키는 영문, 한글버전 순으로 작성합니다.
  - branch를 유지 또는 자유로운 삭제를 위해 자동삭제를 하지 않습니다.

- **깃허브 협업환경 설정**
  - 이슈작성부터 pull request를 통한 코드리뷰, kanban board로 업무 프로세스 관리합니다.
  - 토의를 통해 [깃 컨벤션](https://github.com/4Eat42/yebalja.com/wiki/Conventions)을 수립했습니다

- **역할분배**
  - taelee42 : 예발자 소개 위키를 작성했습니다.
  - 365kim : 위키 구조, 페이지 설계, useful links 링크를 취합했습니다.
  - hidaehyunlee: 깃, 코드컨벤션을 작성했습니다.
  - seongsangCHO : 1주차 개발로그를 작성했습니다.

- **할 일**
  - 강의를 통해 웹, 서버, 데이터베이스에 대해 이해합니다.
    - NODE.JS 강의 완강
    - [node.JS](https://opentutorials.org/course/3332)
    - [node.JS express](https://opentutorials.org/course/3370)
    - 데이터베이스 강의 완강
      - [mysql 기초](https://opentutorials.org/course/3161)
      - [node.JS로 mysql실습](https://opentutorials.org/course/3347)
  - (+)추가 학습링크 : [HTML](https://opentutorials.org/course/3084), [CSS](https://opentutorials.org/course/3086), [JS](https://opentutorials.org/course/3085)
  - 모임(06.15(월))까지 각자 5트랙으로 구현하여 pull request합니다.
    - 페이지에 필요한 데이터베이스 설계 또는 학습하면서 설계
    - node.JS로 서버 구현, 구동
  - 익숙해지기위해 이슈부터 풀리퀘스트까지 직접 해봅시다!

**Comment by 365kim** [comment]
라멘모토에서 시작한 우리팀의 첫 회-의
깔끔한 정리감사 드립니다!

회의당시 06.15(월)까지 각자 5트랙으로 구현하기로 했지만...
저의 기초지식 부족으로 Database, MySQL, nodeJS, Express 이론학습에 시간을 보냈습니다 😅

**Comment by kirrikirri42** [comment]
6.15(월)까지 생활코딩에서 아래 강좌들로 학습했습니다.
[Node.js](https://opentutorials.org/course/3332)
[DATABASE1](https://opentutorials.org/course/3162) [DATABASE2-MySQL](https://opentutorials.org/course/3161)
[Node.js MySQL](https://opentutorials.org/course/3347)
[Node.js Express](https://opentutorials.org/course/3370)

데이터베이스의 서버 연동까지는 학습 시간이 부족했고
프론트 팀에 합류할 생각으로 먼저 React 공부를 시작했습니다.
[제로초의 React로 웹게임 만들기](https://www.youtube.com/watch?v=V3QsSrldHqI&list=PLcqDmjxt30RtqbStQqk-eYMK8N-1SYIFn&index=1)
