### ISSUE TITLE
[Dev_log] 4 Aug(Tue)

### ISSUE THREAD

**Issue by taelee42** [FiveEat42/yebalja.com#71]
# 200804 화 dev log

### mysql DB Convetion

- Table
  - Use lower case
  - Use name in plural
  - Replace space with underscore

- Field 
  - Use lower case
  - Use name in singular
  - Don't use prefix접두사는 쓰지 않고 접미사만 특별한 type의 경우 사용한다.(flag, date등) 
    - 예) start_date, codingbadge_flag
  - 띄어쓰기는 `_`로 표시

## 5.  :paw_prints:To-do

**8.4 (Tue.) ~ 8.7(Fri.)**

#### 1. Front

- [ ] Complete dummy data in badge component `jehong`

- [x] Change date in timeline list to date and time타임라인 카드에 시간적용 `jehong` 

- [ ] Use flex in timeline `jehong`

- [x] Make rolling text automated from DB data(추가 데이터가 있을때 자동 적용, 시간 조건에 맞는 데이터만 표시) `mihykim`

- [x] Add dummy data in review component `daelee`

#####   final

- [x] Favicon, Logojehong`
- [x] About page: `mihykim`
- [x] Rewrite script on yebalja.com `daelee`

#### 2. Back

- [x] Move all the dummy data in Mysql DB
- [x] Send json from DB on api.yeabalja.com
- [x] With using axios, read json in front-end
- [x] Use redux and pass json to each component
- [ ] 

---

### mysql DB Convetion

- Table
  - 소문자만 사용
  - 복수형
  - 띄어쓰기는 `_`로 표시

- Field 
  - 소문자만 사용 
  - 단수형
  - 접두사는 쓰지 않고 접미사만 특별한 type의 경우 사용한다.(flag, date등) 
    - 예) start_date, codingbadge_flag
  - 띄어쓰기는 `_`로 표시

## 5. 🐾할 일이 있습니다.

**8월 4일(화) ~ 8월 7일(금)**

#### 1. 프론트

- [ ] badge 더미데이터 만들고 컴포넌트화 `jehong`

- [x] 타임라인 카드에 시간적용 `jehong` 

- [ ] 타임라인 flex 적용 `jehong`

- [x] 롤링텍스트 애니메이션 수정 `mihykim`

- [x] 롤링텍스트 누르면 목록뜨게 수정 `mihykim`

- [x] 롤링텍스트 데이터 데이터에 따른 자동화(추가 데이터가 있을때 자동 적용, 시간 조건에 맞는 데이터만 표시) `mihykim`

- [x] review 더미데이터 입력 추가(쏘마랑 멋사 부분) `daelee`

#####   마무리

- [x] 파비콘, 로고 : 디벨롭하기`jehong`
- [x] about페이지: `mihykim`
- [x] 문구수정 `daelee`

#### 2. 백

- [x] 더미데이터 DB에 전부 담기
- [x] DB를 바탕으로 api.yebalja.com으로 json쏴주기
- [x] axios로 json 프론트에서 받아들이기
- [x] 리덕스 적용해서 각 컴포넌트에서 읽어들이기

**Comment by 365kim** [comment]
왕
끝이 보입니다
프로젝크 마지막 데브로그를 맡아주셔서 감사합니다!
제 차례 같았는데 당시 컨디션상 차마 손을 들지 못했습니다... 다음 프로젝트의 첫 데브로그는 꼭 저로 시켜주세연!!ㅎㅎㅎ
깔끔하게 정리해주셔서 감사합니다~~~

**Comment by SeongsangCHO** [comment]
정리해주셔서 감사합니다.

금요일까지 달려달려!!!!!!
