### ISSUE TITLE
[Dev_log] 12 June (Fri)

### ISSUE THREAD

**Issue by SeongsangCHO** [FiveEat42/yebalja.com#8]
### :paw_prints: THINKING

- **Design a DB for the YEALY schedule page**
  - Have to decide how to divide Fron and Back-end teams and which parts to take on.
  - In Front-end part, Have to decide whether to implement all of the parts purely using HTML, CSS or using bootstrap and library.
  - Have to decide whether to use a template such as jade, pug, or ejs for view.

### :paw_prints: LEARNED

- Using express, I found that code is compact and I can simplify the connection with the database.
- Can integrate MySQL in nodeJS and process the data through query statements.
- Can write HTML, CSS using JavaScript.
- Can write a table and understand elements(th, tr, td).
- Understanding MVC patterns

### :paw_prints: DECIDED

- Tue - Sat, screen sharing is progressed through google hangout until 10AM to 17PM, so we can respond anytime.
- Efficient development is conducted using the design pattern.
- Until next Monday, the common learning part is completed and development begins
- **Dev env**
  - Framework : nodeJS express
  - Language : JavaScript
  - Database : MySQL
  - Database tool : workbench
    <br>
---

### :paw_prints:고민입니다.

- **연간일정페이지(main)에 대한 DB디자인을 해야합니다.**
  - 프론트,백엔드의 팀을 어떻게 나누고 어떤 파트를 맡아야할지 결정해야합니다.
  - 프론트에서 처음부터 모든 부분을 순수구현할지, 부트스트랩이나 라이브러리를 이용해 구현할지 결정해야합니다.
  - nodejs의 view를 위한 jade, pug등 템플릿에 대한 사용여부를 결정합니다.

### :paw_prints:배웠습니다.

- express로 코드의 양이 간결해지고 데이터베이스와의 연동을 간단하게 할 수 있다는 것을 알게되었습니다.
- nodeJS에서 mysql을 연동하고 쿼리문을 통해 데이터를 처리할 수 있습니다.
- JS로 HTML, CSS를 함께 다루어 작성할 수 있습니다.
- 테이블요소(th, tr, td)에 대해 이해하고 작성할 수 있습니다
- 디자인패턴중 MVC패턴에 대해 이해했습니다.

### :paw_prints:정했습니다.

- 화요일 - 토요일 10 - 17시까지 구글 hangout으로 화면공유 진행하며, 언제든 질의응답 가능할 수 있도록 합니다.
- 프론트, 백으로 팀을 나누어 각 인원마다 파트를 나누어 진행합니다.
- 디자인패턴을 이용해 효율적인 개발을 진행하도록 합니다.
- 월요일까지 공통된 부분 학습을 마무리하고, 개발에 착수합니다.
- **개발환경**
  - 프레임워크 : nodejs express
  - 언어 : JavaScript
  - 데이터베이스 : mysql
  - 데이터베이스 툴 : workbench
    <br>

**Comment by 365kim** [comment]
이 날은 첫회의 이후 중간점검을 한 날이었죠우~
중간점검 이후 @taelee 님께서 정리해주신

#### 연간일정/세부사항 페이지까지의 일 
- 프론트, 백팀으로 나누고 그 안에서 파트 맡아서 진행하기
- Front팀 (예상)
    - 연간 데이터
    - Back에서 만든 연간 데이터를 바탕으로 연간일정 구현
    - 연간데이터 밑에 각 프로그램별 간단 비교 표 만들기
    - 상세 페이지
    - 프로그램별 상세소개는 대부분 프론트에서 바로 구현하시면 될듯(?)
    - 프로그램별 월간 일정은 백에서 데이터 만들어서 구현
- Back팀 (예상)
    - 서버구현 
    - 서버 aws에 올리기
    - db디자인, 구현

#### 이후에는
- 프로젝트가 동시에 끝나면 좋겠지만 그렇지 않은 경우가 많을테니 한쪽 팀이 해야할 일이 끝나기 전에 다음 기획잡아서 해야할 일 정하고 어느정도 진행 하다가 팀 바꾸기
- 프로젝트는 동시에 못 끝내더라도 그안에 맡은 작은 파트는 두팀이 어느정도 비슷한 시점에 끝내고 팀 바꾸기
- 팀 바꿀때 전원이 바꾸기 보단 한,두명만 교체하는건 어떠신가요? 안바꾸고 남은 팀원이 새로온 팀원에게 상황이나 코드설명해주는게 좋을거 같기도 해서요. 근데 다른팀에 있어도 설명해줄수 있을거 같기도 하고 잘 모르겠어요(의견 구합니다.)

**Comment by 365kim** [comment]
#### MVC 디자인패턴
- [Node : MVC 패턴 뼈대 만들기 ( Express 사용 )](https://blog.naver.com/PostView.nhn?blogId=psj9102&logNo=221282415870&categoryNo=40&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView)
- [MVC패턴 설명](https://m.blog.naver.com/jhc9639/220967034588)
- 서로 분리되어 각자의 역할에 집중할 수 있게끔하여 개발을 하고 그렇게 애플리케이션을 만든다면, 유지보수성, 애플리케이션의 확장성, 그리고 유연성이 증가하고, 중복코딩이라는 문제점 또한 사라지게 되는 것입니다.  그러기 위한 MVC패턴입니다.
- 아래는 @secho님의 MVC 설명입니다 (감사합니당!)
    - 서버측(model + controller) / 프론트(html + css + js)
```
사용자(페이지접속)

view : 야 이 URL로 요청왔어 게시글 보여줘야대 게시글 목록이랑 필요한거 줘바
controller:하,, ㅇㅋ 필요한 메소드 내가 호출해서 데이터 뿌려줌 야 model 데이터 담을 준비해 DB에 접근해서 니한테 던질거임
model:하.. ㅇㅋ,, 데이터 담을 클래스(구조체) 만들어 놓겠음..
DB: 야 니가 요청한 데이터야 받아가
model : ㅇㅇ 받음, controller야 이제 어떡함?
controller : ㅇㅇ 확인함. 요청받은 URL로 데이터 넘겨주겠음. 야 View. 이 URL에 해당하는 구조가 담긴 파일에다가 이 데이터 던진다.
view : ㅇㅇ 주셈 틀 다 만들어놈 여기다가 보여줌
```

**Comment by 365kim** [comment]
@taelee42 님피셜
express-generator 가 필수 미들웨어(npm 패키지)들이랑 폴더구조 잡아주는데 
이때 routes(라우팅), views, public(img, css같은 정적 파일들) 이렇게 잡아주네요. 
routes가 controller역할해주고 model만 추가하면 MVC패턴으로 만들어서 할수 있을거 같아요.

**Comment by 365kim** [comment]
#### 템플릿엔진
- [Node.js - ejs 와 jade를 비교 살펴보기](https://gocoder.tistory.com/1033)

**Comment by 365kim** [comment]
#### 프론트엔드 프레임워크
- react, vue, angular 삼대장  점유율 [비교](https://existek.com/blog/top-front-end-frameworks-2020/)
![ff](https://user-images.githubusercontent.com/60066472/84784842-baa6e600-b025-11ea-9141-330a177606a7.png)
- [Angular, React, Vew가 뭔가요?](https://www.youtube.com/watch?v=iE29lbjbow0)

**Comment by SeongsangCHO** [comment]
@365kim 댓글로 추가사항 작성 감사합니다!
