### ISSUE TITLE
Front-End Framework(React) Preview

### ISSUE THREAD

**Issue by 365kim** [FiveEat42/yebalja.com#9]
- __Who__: Each member of the front team 
- __What__: will continue learning about the chosen front-end framework, React and other things if needed
- __Why__: to build abilities to implement the frontside
- __When__: Until this Friday (Extend the deadline if necessary)
<br>

---
- __누가__:  프론트엔드 팀원들
- __무엇을__: 채택한 웹프레임워크 리액트 관련 학습 진행
- __왜__:  프론트엔드 구현에 필요한 스킬을 습득하기 위해
- __언제__:  이번주 금요일까지 (필요시 기한 연장)

**Comment by 365kim** [comment]
저는 아래강의 위주로 학습하려고 합니당
- [ ] 생활코딩 [JavaScript](https://opentutorials.org/course/3085) 가능하면 전강의
- [ ] Zerocho [리액트(웹게임)](https://www.youtube.com/playlist?list=PLcqDmjxt30RtqbStQqk-eYMK8N-1SYIFn) 게임 2~3개?!
- [ ] 누구든지 하는 [리액트](https://www.youtube.com/watch?v=fT9iFFAt60E&list=PL9FpF_z-xR_E4rxYMMZx5cOpwaiwCzWUH&index=1)  가능하면 전강의

시간이 되면 오늘 회의때 @SeongsangCHO 께서 던져주신 키워드 __부트스트랩__ 도 용법을 찾아보려고 합니당

**Comment by hidaehyunlee** [comment]
후론트엔드 label 색이 참 맘에 드는군요. 

전 우선 아래 위키를 정독하면서 자바 공부하려구요.
- [ ] [모던 JavaScript 튜토리얼](https://ko.javascript.info/)

**Comment by kirrikirri42** [comment]
전 제로초의 [리액트(웹게임)](https://www.youtube.com/playlist?list=PLcqDmjxt30RtqbStQqk-eYMK8N-1SYIFn)을 마저 공부하고
제로초의 [리액트(노드버드)](https://www.youtube.com/playlist?list=PLcqDmjxt30RujZzqIS1sAHz92TZDaRB9d)를 볼 계획입니다.

**Comment by 365kim** [comment]
앗 노드버드를 깜빡하고 있었군요..!!
저도 웹게임 한두개만 보고 노드버드로 건너뛸까싶습니다

**Comment by 365kim** [comment]
추가로 생활코딩 CSS, 제로초님 CSS, 나동빈님의 부트스트랩을 조금씩 학습했습니다.
