### ISSUE TITLE
Need all the stack logos

### ISSUE THREAD

**Issue by kirrikirri42** [FiveEat42/yebalja.com#98]
### 🤔 What kinds of logos to look for?
- The more square the better
- Please find svg files or png
- For non-vector logos, please make sure that each logo's width is at least 30px. Even better if it's over 60px.

---

#### 2. [Add them directly at Figma](https://www.figma.com/file/u3D6M6PJ0zZEaSWVF4qVhB/%EB%A1%9C%EA%B3%A0-%EB%AA%A8%EC%9D%8C)
- Like this
  <img src="https://user-images.githubusercontent.com/52592748/99480891-573a2f00-299c-11eb-8b7c-173420c23af8.png" width="200"/>

---

##### Check out this [Notion Link](https://www.notion.so/2c3a0549f37b4f288c2ff7f82bc95c76)
- This link is for yebalja.com team only

#### 🤓 Logo sites
[seeklogo](https://seeklogo.com/)
[iconscout](https://iconscout.com/)
[worldvectorlogo](https://worldvectorlogo.com/)
- Figma can't process eps format files

<br><br>

---

<br><br>

### 🤔 이런 로고를 찾아주세요
- 최대한 정사각형이나 원에 가까운 로고를 찾아주세요
- svg나 배경이 없는 png로 부탁드려요
- 벡터파일이 아닌경우 최소 30픽셀로 부탁드려요! 60픽셀 이상이면 아주 칭찬해!

---

#### 2. [피그마에서 바로 추가해주세요](https://www.figma.com/file/u3D6M6PJ0zZEaSWVF4qVhB/%EB%A1%9C%EA%B3%A0-%EB%AA%A8%EC%9D%8C)
- 요로코롬
  <img src="https://user-images.githubusercontent.com/52592748/99480891-573a2f00-299c-11eb-8b7c-173420c23af8.png" width="200"/>

---

##### [노션 링크](https://www.notion.so/2c3a0549f37b4f288c2ff7f82bc95c76)를 참고해 어떤 로고가 필요한지 확인하세용
- 예발자팀 전용 링크입니다
#### 🤓 참고 로고 사이트
[seeklogo](https://seeklogo.com/)
[iconscout](https://iconscout.com/)
[worldvectorlogo](https://worldvectorlogo.com/)
- eps 형식은 피그마에 안 들어갑니당

**Comment by 365kim** [comment]
![image](https://user-images.githubusercontent.com/60066472/99496159-1b609300-29b7-11eb-85f6-44915be2184f.png)
정아님 검나 친절쓰 🥰😍🥰😍 감사합니다!

제가 담당한 DBMS 로고들 figma에 추가했습니당!
투명배경 도저히 안나오는 포스트그레는 흰바탕인 png로 넣어두었어요 ㅜㅜ
감사합니당!!

**Comment by SeongsangCHO** [comment]
추가했습니다~~

**Comment by hidaehyunlee** [comment]
프론트 프레임워크 추가했습니다! 취합 감사합니다

**Comment by kirrikirri42** [comment]
감사합니다!
